import { useMemo, useRef, useState } from 'react'
import { supabase } from '../../lib/supabase'
import type { Json } from '../../types/database'
import { findDuplicate } from './deduplication'
import { buildFinanceImportPrompt } from './prompt'
import { analyzeFinanceImport, decimalStringToMinor, normalizeDescription, sha256, type FinanceImportPayload, type ImportIssue, type ImportStatement } from './importSchema'
import { type Account, type Category, type Transaction, useFinanceImportMutations } from '../finance'

type Props = { userId: string; accounts: Account[]; categories: Category[]; transactions: Transaction[]; hidden: boolean; onClose: () => void }
type Mapping = { accountId: string; createName: string; categoryByName: Record<string, string>; reviewByIndex: Record<string, 'pending' | 'resolved' | 'excluded'> }

export function FinanceImportModal({ userId, accounts, categories, transactions, hidden, onClose }: Props) {
  const [text, setText] = useState(''); const [payload, setPayload] = useState<FinanceImportPayload | null>(null); const [mappings, setMappings] = useState<Mapping[]>([]); const [error, setError] = useState<string | null>(null); const [issues, setIssues] = useState<ImportIssue[]>([]); const [analysisStatus, setAnalysisStatus] = useState<string | null>(null); const [allowPending, setAllowPending] = useState(false); const [busy, setBusy] = useState(false); const [done, setDone] = useState(false); const fileInput = useRef<HTMLInputElement>(null); const mutations = useFinanceImportMutations(userId)
  const prompt = useMemo(() => buildFinanceImportPrompt(categories), [categories])
  const copy = async () => { try { await navigator.clipboard.writeText(prompt); setError(null) } catch { setError('No se pudo copiar el prompt. Copialo manualmente.') } }
  const parse = () => { setAnalysisStatus('Analizando JSON…'); const result = analyzeFinanceImport(text); setIssues(result.issues); if (!result.payload) { setPayload(null); setError(result.issues.length ? 'Encontramos datos para corregir antes de continuar.' : 'No se pudo validar el JSON.'); setAnalysisStatus(`Análisis terminado: ${result.issues.length} problema${result.issues.length === 1 ? '' : 's'} encontrado${result.issues.length === 1 ? '' : 's'}.`); return }; setPayload(result.payload); setMappings(result.payload.statements.map((statement) => ({ accountId: accounts.find((account) => account.currency === statement.currency && account.name.toLowerCase() === statement.account_label.toLowerCase())?.id ?? '', createName: `${statement.institution} · ${statement.account_label}`, categoryByName: {}, reviewByIndex: {} }))); setError(null); setAnalysisStatus(`Análisis correcto: ${result.payload.statements.length} resumen${result.payload.statements.length === 1 ? '' : 'es'} detectado${result.payload.statements.length === 1 ? '' : 's'}.`) }
  const repair = (issue: ImportIssue) => { if (!issue.repair) return; try { const raw: unknown = JSON.parse(text); if (!raw || typeof raw !== 'object' || Array.isArray(raw)) throw new Error(); const root = raw as { statements?: unknown[] }; const statement = root.statements?.[issue.repair.statementIndex]; if (!statement || typeof statement !== 'object' || Array.isArray(statement)) throw new Error(); const transactions = (statement as { transactions?: unknown[] }).transactions; const transaction = transactions?.[issue.repair.transactionIndex]; if (!transaction || typeof transaction !== 'object' || Array.isArray(transaction)) throw new Error(); if (issue.repair.kind === 'remove_transaction') transactions!.splice(issue.repair.transactionIndex, 1); else { const row = transaction as Record<string, unknown>; const malformed = Object.keys(row).find((key) => key.startsWith('suggested_category')); row.suggested_category = malformed ? row[malformed] : null; if (malformed) delete row[malformed] }; const next = JSON.stringify(raw, null, 2); setText(next); setError(null); setIssues([]); setAnalysisStatus('Corrección aplicada. Volvé a analizar el JSON.'); } catch { setError('No se pudo aplicar la corrección automática. Podés eliminar esa fila o pegar un JSON nuevo.') } }
  const setMapping = (index: number, update: Partial<Mapping>) => setMappings((current) => current.map((mapping, item) => item === index ? { ...mapping, ...update } : mapping))
  const unresolved = payload?.statements.some((statement, index) => !mappings[index]?.accountId && !mappings[index]?.createName.trim() || (!allowPending && statement.transactions.some((transaction, row) => mappings[index]?.reviewByIndex[row] !== 'excluded' && (!resolveCategory(transaction, row, mappings[index], categories) || ((transaction.needs_review || transaction.possible_duplicate || transaction.type === 'transfer' || transaction.type === 'card_payment') && mappings[index]?.reviewByIndex[row] !== 'resolved'))))) ?? true
  const confirm = async () => {
    if (!payload || unresolved) return; setBusy(true); setError(null)
    try {
      for (const [statementIndex, statement] of payload.statements.entries()) {
        const mapping = mappings[statementIndex]; let account = accounts.find((item) => item.id === mapping.accountId)
        if (!account) { const created = await supabase.from('finance_accounts').insert({ user_id: userId, name: mapping.createName.trim(), account_type: accountType(statement.account_type), currency: statement.currency, balance_role: statement.account_type === 'credit_card' ? 'liability' : 'operational' }).select().single(); if (created.error || !created.data) throw new Error(created.error?.message ?? 'No se pudo crear la cuenta.') ; account = created.data }
        await importStatement(statement, mapping, account, payload, transactions, mutations, categories)
      }
      setDone(true)
    } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo confirmar la importación.') } finally { setBusy(false) }
  }
  return <div className="home-modal-backdrop" role="presentation"><section aria-labelledby="finance-import-title" aria-modal="true" className="home-modal finance-import-modal" role="dialog"><header className="section-heading"><div><p className="eyebrow">Importación asistida</p><h2 id="finance-import-title">Importar resumen</h2></div><button className="text-button" onClick={onClose} type="button">Cerrar</button></header>{error && <p aria-live="polite" className="form-error">{error}</p>}
    {!payload && !done && <div className="task-form"><p>Copiá el prompt, adjuntá los resúmenes en ChatGPT y pegá aquí el JSON que devuelva. Momentum no envía archivos ni se conecta con OpenAI.</p><textarea aria-label="Prompt listo para copiar" readOnly value={prompt} /><button className="secondary-button" onClick={copy} type="button">Copiar prompt</button><label>Pegá el JSON<textarea aria-label="JSON de resúmenes" value={text} onChange={(event) => setText(event.target.value)} /></label><input accept="application/json,.json" className="sr-only" ref={fileInput} type="file" onChange={(event) => { const file = event.target.files?.[0]; if (file) file.text().then(setText).catch(() => setError('No se pudo leer el archivo.')) }} />{analysisStatus && <p aria-live="polite" className="finance-import-status">{analysisStatus}</p>}{issues.length > 0 && <section aria-live="polite" className="finance-import-issues"><strong>Corregí estos datos:</strong><ul>{issues.map((issue, index) => <li key={`${issue.path}-${index}`}><b>{issue.path}:</b> {issue.message}{issue.repair && <button onClick={() => repair(issue)} type="button">{issue.repair.kind === 'restore_suggested_category' ? 'Corregir automáticamente' : 'Eliminar fila'}</button>}</li>)}</ul></section>}<div className="task-form-actions"><button className="secondary-button" onClick={() => fileInput.current?.click()} type="button">Subir .json</button><button className="primary-button" disabled={!text.trim()} onClick={parse} type="button">Analizar JSON</button></div></div>}
    {payload && !done && <><div className="finance-import-summary"><strong>{payload.statements.length} cuenta{payload.statements.length === 1 ? '' : 's'} detectada{payload.statements.length === 1 ? '' : 's'}</strong><span>{unresolved ? 'Resolvé cuentas o importá pendientes' : 'Listo para confirmar'}</span></div>{payload.statements.map((statement, index) => <StatementReview accountList={accounts} categories={categories} hidden={hidden} key={`${statement.institution}-${statement.account_label}`} mapping={mappings[index]} onChange={(update) => setMapping(index, update)} statement={statement} />)}<label className="finance-import-pending"><input checked={allowPending} onChange={(event) => setAllowPending(event.target.checked)} type="checkbox" />Importar sin categoría y pendientes para revisar después. No afectarán saldo, presupuesto ni informes.</label><div className="task-form-actions"><button className="secondary-button" onClick={() => setPayload(null)} type="button">Cambiar JSON</button><button className="primary-button" disabled={busy || unresolved} onClick={confirm} type="button">{busy ? 'Confirmando…' : 'Confirmar importación'}</button></div></>}
    {done && <div className="finance-import-done"><strong>Importación confirmada</strong><p>Los movimientos se registraron después de la revisión final.</p><button className="primary-button" onClick={onClose} type="button">Cerrar</button></div>}
  </section></div>
}

function StatementReview({ statement, mapping, accountList, categories, hidden, onChange }: { statement: ImportStatement; mapping: Mapping; accountList: Account[]; categories: Category[]; hidden: boolean; onChange: (value: Partial<Mapping>) => void }) {
  const matching = accountList.filter((account) => account.currency === statement.currency && account.is_active)
  return <article className="finance-import-statement"><h3>{statement.institution} · {statement.account_label}</h3><p>{statement.account_type} · {statement.currency} · {statement.period_start} a {statement.period_end}</p><div className="task-form-grid"><label>Cuenta de Momentum<select value={mapping.accountId} onChange={(event) => onChange({ accountId: event.target.value })}><option value="">Crear una cuenta al confirmar</option>{matching.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select></label>{!mapping.accountId && <label>Nueva cuenta<input value={mapping.createName} onChange={(event) => onChange({ createName: event.target.value })} /></label>}</div><div className="finance-import-list">{statement.transactions.map((transaction, index) => <article className={`finance-import-row ${mapping.reviewByIndex[index] === 'excluded' ? 'finance-import-row--excluded' : ''}`} key={`${transaction.date}-${index}`}><div><strong>{hidden ? '••••' : transaction.amount}</strong><p>{transaction.original_description}</p><small>{transaction.date} · {transaction.type} · confianza {transaction.confidence}%{transaction.installment ? ` · cuota ${transaction.installment.current}/${transaction.installment.total}` : ''}</small>{(transaction.needs_review || transaction.possible_duplicate || transaction.possible_reimbursement) && <small className="finance-import-warning">{transaction.review_reason ?? (transaction.possible_duplicate ? 'Posible duplicado' : 'Posible reintegro')}</small>}</div><div className="finance-import-controls"><label><span>Categoría</span><select value={mapping.categoryByName[index] ?? resolveCategory(transaction, index, mapping, categories) ?? ''} onChange={(event) => onChange({ categoryByName: { ...mapping.categoryByName, [index]: event.target.value } })}><option value="">Resolver categoría</option>{categories.filter((category) => category.is_active && (category.category_type === 'both' || category.category_type === expectedType(transaction.type))).map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label><span>Revisión</span><select value={mapping.reviewByIndex[index] ?? ((transaction.needs_review || transaction.possible_duplicate || transaction.type === 'transfer' || transaction.type === 'card_payment') ? 'pending' : 'resolved')} onChange={(event) => onChange({ reviewByIndex: { ...mapping.reviewByIndex, [index]: event.target.value as 'pending' | 'resolved' | 'excluded' } })}><option value="resolved">Mantener</option><option value="pending">Requiere revisión</option><option value="excluded">Excluir fila</option></select></label></div></article>)}</div></article>
}

const expectedType = (type: string) => type === 'income' ? 'income' : 'expense'
const resolveCategory = (transaction: ImportStatement['transactions'][number], index: number, mapping: Mapping | undefined, categories: Category[]) => mapping?.categoryByName[index] ?? categories.find((category) => category.is_active && category.name.toLocaleLowerCase() === transaction.suggested_category?.toLocaleLowerCase() && (category.category_type === 'both' || category.category_type === expectedType(transaction.type)))?.id ?? null
const accountType = (type: ImportStatement['account_type']) => type === 'bank_account' ? 'bank' : type === 'digital_wallet' ? 'digital_wallet' : type === 'cash' ? 'cash' : 'other'

async function importStatement(statement: ImportStatement, mapping: Mapping, account: Account, payload: FinanceImportPayload, existing: Transaction[], mutations: ReturnType<typeof useFinanceImportMutations>, categories: Category[]) {
  const payloadHash = await sha256(JSON.stringify({ statement, schema_version: payload.schema_version })); const fingerprint = await sha256(JSON.stringify(statement.transactions.map((row) => [row.date, row.amount, row.type, row.description])))
  const batch = await mutations.createBatch.mutateAsync({ account_id: account.id, statement_type: statement.account_type === 'credit_card' ? 'credit_card' : 'bank_account', currency: account.currency, period_start: statement.period_start, period_end: statement.period_end, schema_version: payload.schema_version, source_name: statement.institution, statement_reference: statement.account_label, raw_payload: payload as unknown as Json, payload_hash: payloadHash, statement_fingerprint: fingerprint, status: 'reviewing', total_items: statement.transactions.length })
  const items = await Promise.all(statement.transactions.map(async (transaction, index) => { if (mapping.reviewByIndex[index] === 'excluded') return null; const type = expectedType(transaction.type); const amountMinor = decimalStringToMinor(transaction.amount); const description = normalizeDescription(transaction.description); const hash = await sha256([account.id, statement.currency, transaction.date, type, amountMinor, description, index].join('|')); const duplicate = findDuplicate({ account_id: account.id, transaction_type: type, amount_minor: amountMinor, occurred_on: transaction.date, description_normalized: description, external_id: null }, existing); const categoryId = resolveCategory(transaction, index, mapping, categories); const pending = !categoryId || mapping.reviewByIndex[index] === 'pending' || transaction.needs_review || transaction.type === 'transfer' || transaction.type === 'card_payment'; return { source_index: index, included: true, occurred_on: transaction.date, description_original: transaction.original_description, description_normalized: description, amount_minor: amountMinor, transaction_type: type, category_id: categoryId, transaction_hash: hash, confidence: transaction.confidence, review_required: pending, review_reason: pending ? transaction.review_reason ?? 'Pendiente de revisión manual.' : null, warnings: [] as unknown as Json, duplicate_status: duplicate ? 'accepted' : 'none', duplicate_candidate_transaction_id: duplicate?.transaction.id ?? null, reimbursement_status: transaction.possible_reimbursement ? 'suggested' : 'none', reimbursement_reason: transaction.related_transaction_hint } })).then((rows) => rows.filter((row): row is NonNullable<typeof row> => row !== null))
  await mutations.replaceItems.mutateAsync({ batchId: batch.id, items }); await mutations.confirmBatch.mutateAsync(batch.id)
}
