export const FINANCE_IMPORT_VERSION = 'momentum.finance_statement.v2'
export type DetectedAccountType = 'bank_account' | 'credit_card' | 'cash' | 'digital_wallet' | 'other'
export type DetectedTransactionType = 'income' | 'expense' | 'transfer' | 'card_payment'
export type ImportTransaction = { date: string; description: string; original_description: string; amount: string; type: DetectedTransactionType; suggested_category: string | null; installment: { current: number; total: number } | null; confidence: number; needs_review: boolean; review_reason: string | null; possible_duplicate: boolean; possible_reimbursement: boolean; related_transaction_hint: string | null }
export type ImportStatement = { institution: string; account_label: string; account_type: DetectedAccountType; currency: string; period_start: string; period_end: string; transactions: ImportTransaction[] }
export type FinanceImportPayload = { schema_version: typeof FINANCE_IMPORT_VERSION; statements: ImportStatement[] }
export type ImportIssue = { path: string; message: string; repair?: { kind: 'restore_suggested_category' | 'remove_transaction'; statementIndex: number; transactionIndex: number } }

const obj = (value: unknown, label: string): Record<string, unknown> => { if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error(`${label} debe ser un objeto.`); return value as Record<string, unknown> }
const keys = (value: Record<string, unknown>, allowed: string[], label: string) => { const extra = Object.keys(value).find((key) => !allowed.includes(key)); const missing = allowed.find((key) => !(key in value)); if (extra) throw new Error(`${label} contiene “${extra}”, que no está permitido.`); if (missing) throw new Error(`${label} requiere “${missing}”.`) }
const text = (value: unknown, label: string): string => { if (typeof value !== 'string' || !value.trim()) throw new Error(`${label} debe ser texto no vacío.`); return value.trim() }
const nullableText = (value: unknown, label: string): string | null => value === null ? null : text(value, label)
const date = (value: unknown, label: string) => { const result = text(value, label); if (!/^\d{4}-\d{2}-\d{2}$/.test(result) || Number.isNaN(Date.parse(`${result}T00:00:00Z`))) throw new Error(`${label} debe usar AAAA-MM-DD.`); return result }
export function decimalStringToMinor(value: string): number { if (!/^\d+(\.\d{1,2})?$/.test(value)) throw new Error('El importe debe ser un decimal positivo como texto, con hasta dos decimales.'); const [whole, decimals = ''] = value.split('.'); const minor = Number(whole) * 100 + Number(`${decimals}00`.slice(0, 2)); if (!Number.isSafeInteger(minor) || minor <= 0) throw new Error('El importe está fuera de rango.'); return minor }

export function parseFinanceImport(input: string): FinanceImportPayload {
  if (input.length > 2_000_000) throw new Error('El JSON supera el límite de 2 MB.')
  let raw: unknown; try { raw = JSON.parse(input) } catch { throw new Error('El contenido no es JSON válido.') }
  const root = obj(raw, 'El JSON'); keys(root, ['schema_version', 'statements'], 'El JSON')
  if (root.schema_version !== FINANCE_IMPORT_VERSION) throw new Error(`schema_version debe ser ${FINANCE_IMPORT_VERSION}.`)
  if (!Array.isArray(root.statements) || !root.statements.length || root.statements.length > 20) throw new Error('statements debe contener entre 1 y 20 resúmenes.')
  const statements = root.statements.map((source, statementIndex): ImportStatement => {
    const label = `statements[${statementIndex}]`; const statement = obj(source, label); keys(statement, ['institution', 'account_label', 'account_type', 'currency', 'period_start', 'period_end', 'transactions'], label)
    const accountType = text(statement.account_type, `${label}.account_type`); if (!['bank_account', 'credit_card', 'cash', 'digital_wallet', 'other'].includes(accountType)) throw new Error(`${label}.account_type no es válido.`)
    const currency = text(statement.currency, `${label}.currency`).toUpperCase(); if (!/^[A-Z]{3}$/.test(currency)) throw new Error(`${label}.currency debe ser ISO-4217.`)
    const start = date(statement.period_start, `${label}.period_start`); const end = date(statement.period_end, `${label}.period_end`); if (end < start) throw new Error(`${label} tiene un período inválido.`)
    if (!Array.isArray(statement.transactions) || statement.transactions.length > 1000) throw new Error(`${label}.transactions debe ser una lista de hasta 1.000 filas.`)
    const transactions = statement.transactions.map((sourceRow, rowIndex): ImportTransaction => {
      const rowLabel = `${label}.transactions[${rowIndex}]`; const row = obj(sourceRow, rowLabel); keys(row, ['date', 'description', 'original_description', 'amount', 'type', 'suggested_category', 'installment', 'confidence', 'needs_review', 'review_reason', 'possible_duplicate', 'possible_reimbursement', 'related_transaction_hint'], rowLabel)
      const transactionType = text(row.type, `${rowLabel}.type`); if (!['income', 'expense', 'transfer', 'card_payment'].includes(transactionType)) throw new Error(`${rowLabel}.type no es válido.`)
      const amount = text(row.amount, `${rowLabel}.amount`); decimalStringToMinor(amount)
      if (typeof row.confidence !== 'number' || !Number.isInteger(row.confidence) || row.confidence < 0 || row.confidence > 100) throw new Error(`${rowLabel}.confidence debe ser un entero entre 0 y 100.`)
      if (typeof row.needs_review !== 'boolean' || typeof row.possible_duplicate !== 'boolean' || typeof row.possible_reimbursement !== 'boolean') throw new Error(`${rowLabel} contiene indicadores booleanos inválidos.`)
      const reason = nullableText(row.review_reason, `${rowLabel}.review_reason`); if (row.needs_review && !reason) throw new Error(`${rowLabel}.review_reason es obligatorio si needs_review es true.`)
      const installment = row.installment === null ? null : (() => { const value = obj(row.installment, `${rowLabel}.installment`); keys(value, ['current', 'total'], `${rowLabel}.installment`); if (!Number.isInteger(value.current) || !Number.isInteger(value.total) || (value.current as number) < 1 || (value.total as number) < (value.current as number)) throw new Error(`${rowLabel}.installment no es válido.`); return { current: value.current as number, total: value.total as number } })()
      return { date: date(row.date, `${rowLabel}.date`), description: text(row.description, `${rowLabel}.description`), original_description: text(row.original_description, `${rowLabel}.original_description`), amount, type: transactionType as DetectedTransactionType, suggested_category: nullableText(row.suggested_category, `${rowLabel}.suggested_category`), installment, confidence: row.confidence, needs_review: row.needs_review, review_reason: reason, possible_duplicate: row.possible_duplicate, possible_reimbursement: row.possible_reimbursement, related_transaction_hint: nullableText(row.related_transaction_hint, `${rowLabel}.related_transaction_hint`) }
    })
    return { institution: text(statement.institution, `${label}.institution`), account_label: text(statement.account_label, `${label}.account_label`), account_type: accountType as DetectedAccountType, currency, period_start: start, period_end: end, transactions }
  })
  return { schema_version: FINANCE_IMPORT_VERSION, statements }
}
export const normalizeDescription = (value: string) => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toUpperCase().replace(/\d{4,}/g, '').replace(/[^A-Z0-9]+/g, ' ').trim().replace(/\s+/g, ' ')
export async function sha256(value: string) { const hash = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(value)); return Array.from(new Uint8Array(hash), (part) => part.toString(16).padStart(2, '0')).join('') }

export function analyzeFinanceImport(input: string): { payload: FinanceImportPayload | null; issues: ImportIssue[] } {
  if (input.length > 2_000_000) return { payload: null, issues: [{ path: 'Archivo', message: 'Supera el límite de 2 MB.' }] }
  let raw: unknown
  try { raw = JSON.parse(input) } catch { return { payload: null, issues: [{ path: 'JSON', message: 'No es JSON válido. Copiá únicamente el bloque JSON, sin Markdown ni texto adicional.' }] } }
  const issues: ImportIssue[] = []; const root = raw !== null && typeof raw === 'object' && !Array.isArray(raw) ? raw as Record<string, unknown> : null
  if (!root) return { payload: null, issues: [{ path: 'JSON', message: 'El contenido debe comenzar con un objeto JSON.' }] }
  const rootExpected = ['schema_version', 'statements']; for (const key of rootExpected) if (!(key in root)) issues.push({ path: 'JSON', message: `Falta “${key}”.` }); for (const key of Object.keys(root)) if (!rootExpected.includes(key)) issues.push({ path: 'JSON', message: `El campo “${key}” no está permitido.` })
  if (root.schema_version !== FINANCE_IMPORT_VERSION) issues.push({ path: 'schema_version', message: `Debe ser “${FINANCE_IMPORT_VERSION}”.` })
  if (!Array.isArray(root.statements)) issues.push({ path: 'statements', message: 'Debe ser una lista de resúmenes.' })
  const statementFields = ['institution', 'account_label', 'account_type', 'currency', 'period_start', 'period_end', 'transactions']; const transactionFields = ['date', 'description', 'original_description', 'amount', 'type', 'suggested_category', 'installment', 'confidence', 'needs_review', 'review_reason', 'possible_duplicate', 'possible_reimbursement', 'related_transaction_hint']
  if (Array.isArray(root.statements)) root.statements.forEach((source, statementIndex) => { const statement = source !== null && typeof source === 'object' && !Array.isArray(source) ? source as Record<string, unknown> : null; const path = `Resumen ${statementIndex + 1}`; if (!statement) { issues.push({ path, message: 'Debe ser un objeto.' }); return }; for (const key of statementFields) if (!(key in statement)) issues.push({ path, message: `Falta “${key}”.` }); for (const key of Object.keys(statement)) if (!statementFields.includes(key)) issues.push({ path, message: `El campo “${key}” no está permitido.` }); if (!Array.isArray(statement.transactions)) { issues.push({ path, message: 'transactions debe ser una lista.' }); return }; statement.transactions.forEach((sourceTransaction, transactionIndex) => { const transaction = sourceTransaction !== null && typeof sourceTransaction === 'object' && !Array.isArray(sourceTransaction) ? sourceTransaction as Record<string, unknown> : null; const transactionPath = `${path}, movimiento ${transactionIndex + 1}`; if (!transaction) { issues.push({ path: transactionPath, message: 'Debe ser un objeto.', repair: { kind: 'remove_transaction', statementIndex, transactionIndex } }); return }; for (const key of transactionFields) if (!(key in transaction)) issues.push({ path: transactionPath, message: `Falta “${key}”.` }); for (const key of Object.keys(transaction)) if (!transactionFields.includes(key)) { const isCorruptedCategory = key.startsWith('suggested_category') && !('suggested_category' in transaction); issues.push({ path: transactionPath, message: `El campo “${key}” no está permitido. Verificá que ChatGPT no haya convertido texto en un enlace.`, repair: isCorruptedCategory ? { kind: 'restore_suggested_category', statementIndex, transactionIndex } : { kind: 'remove_transaction', statementIndex, transactionIndex } }) }; if (typeof transaction.amount !== 'string') issues.push({ path: transactionPath, message: 'amount debe ser un string decimal, por ejemplo “1250.50”, nunca un número.', repair: { kind: 'remove_transaction', statementIndex, transactionIndex } }) }) })
  if (issues.length) return { payload: null, issues: issues.slice(0, 30) }
  try { return { payload: parseFinanceImport(input), issues: [] } } catch (reason) { return { payload: null, issues: [{ path: 'Validación', message: reason instanceof Error ? reason.message : 'El esquema no es válido.' }] } }
}
