import { supabase } from '../lib/supabase'
import type { Database, Json } from '../types/database'

const MAX_FILE_BYTES = 500 * 1024 * 1024
const quantityMap: Record<string, 'steps' | 'distance' | 'activeEnergy' | 'basalEnergy' | 'flights'> = {
  HKQuantityTypeIdentifierStepCount: 'steps', HKQuantityTypeIdentifierDistanceWalkingRunning: 'distance',
  HKQuantityTypeIdentifierActiveEnergyBurned: 'activeEnergy', HKQuantityTypeIdentifierBasalEnergyBurned: 'basalEnergy', HKQuantityTypeIdentifierFlightsClimbed: 'flights',
}
type Daily = { steps: number; distance: number; activeEnergy: number; basalEnergy: number; flights: number; walkingSpeed: number[]; stepLength: number[]; asymmetry: number[]; doubleSupport: number[]; steadiness: number[] }
export type AppleImportResult = { recordsProcessed: number; recordsImported: number; recordsSkipped: number; days: number; weight: number; sleep: number; workouts: number; earliestDate: string | null; latestDate: string | null; warnings: number }
type Progress = (processed: number) => void
const blank = (): Daily => ({ steps: 0, distance: 0, activeEnergy: 0, basalEnergy: 0, flights: 0, walkingSpeed: [], stepLength: [], asymmetry: [], doubleSupport: [], steadiness: [] })
const attrs = (tag: string) => Object.fromEntries([...tag.matchAll(/([\w:]+)="([^"]*)"/g)].map(([, k, v]) => [k, v]))
const parseDate = (value?: string) => value ? new Date(value.replace(' ', 'T').replace(/ ([+-]\d{4})$/, '$1')) : null
const dateKey = (value: Date) => value.toLocaleDateString('en-CA')
const sourceDate = (value: string | undefined, fallback: Date) => /^\d{4}-\d{2}-\d{2}/.exec(value ?? '')?.[0] ?? dateKey(fallback)
const average = (values: number[]) => values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : null
const sleepType = (value?: string) => ({ HKCategoryValueSleepAnalysisInBed: 'in_bed', HKCategoryValueSleepAnalysisAsleep: 'asleep', HKCategoryValueSleepAnalysisAwake: 'awake', HKCategoryValueSleepAnalysisAsleepCore: 'core', HKCategoryValueSleepAnalysisAsleepDeep: 'deep', HKCategoryValueSleepAnalysisAsleepREM: 'rem' }[value ?? ''] ?? 'unknown')

/** Chunked element scanner: it never builds a DOM or resolves XML entities/DTDs. */
export async function importAppleHealth(file: File, userId: string, onProgress: Progress): Promise<AppleImportResult> {
  if (!file.name.toLowerCase().endsWith('.xml')) throw new Error('Seleccioná un archivo XML.')
  if (file.size > MAX_FILE_BYTES) throw new Error('El archivo supera el límite de 500 MB configurado.')
  const created = await supabase.from('health_imports').insert({ user_id: userId, provider: 'apple_health', filename: file.name, file_size: file.size, status: 'processing' }).select().single()
  if (created.error || !created.data) throw new Error(created.error?.message ?? 'No se pudo iniciar la importación.')
  const importId = created.data.id
  try {
    const daily = new Map<string, Daily>(); const weights: Array<{ recorded_at: string; numeric_value: number; external_id: string }> = []; const sleeps: Array<Pick<Database['public']['Tables']['health_sleep_sessions']['Insert'], 'start_at' | 'end_at' | 'sleep_type' | 'source' | 'external_id'>> = []; const workouts: Array<Pick<Database['public']['Tables']['workouts']['Insert'], 'title' | 'activity_type' | 'started_at' | 'duration_minutes' | 'external_id' | 'notes'>> = []
    const ids = new Set<string>(); let processed = 0; let skipped = 0; let warnings = 0; let sawHealthData = false; let buffer = ''; const reader = file.stream().pipeThrough(new TextDecoderStream()).getReader()
      const process = (tag: string) => { const a = attrs(tag); const name = /^<\s*([\w:]+)/.exec(tag)?.[1]; if (!name) return; if (name === 'Record' || name === 'Workout') sawHealthData = true; if (name === 'Record') { processed++; const external = a.uuid; if (external && ids.has(external)) { skipped++; return }; if (external) ids.add(external); const start = parseDate(a.startDate); if (!start) { skipped++; return }; const localDate = sourceDate(a.startDate, start); const type = a.type ?? ''; const value = Number(a.value); if (type in quantityMap && Number.isFinite(value)) { const key = localDate; const day = daily.get(key) ?? blank(); daily.set(key, day); const metric = quantityMap[type]; if (metric === 'distance') day.distance += a.unit === 'm' ? value / 1000 : value; else if (metric === 'steps') day.steps += value; else day[metric] += value; return }
        const walking: Record<string, keyof Daily> = { HKQuantityTypeIdentifierWalkingSpeed: 'walkingSpeed', HKQuantityTypeIdentifierWalkingStepLength: 'stepLength', HKQuantityTypeIdentifierWalkingAsymmetryPercentage: 'asymmetry', HKQuantityTypeIdentifierWalkingDoubleSupportPercentage: 'doubleSupport', HKQuantityTypeIdentifierAppleWalkingSteadiness: 'steadiness' }; if (type in walking && Number.isFinite(value)) { const key = localDate; const day = daily.get(key) ?? blank(); daily.set(key, day); (day[walking[type]] as number[]).push(value); return }
        if (type === 'HKQuantityTypeIdentifierBodyMass' && Number.isFinite(value)) { weights.push({ recorded_at: start.toISOString(), numeric_value: a.unit === 'g' ? value / 1000 : value, external_id: external || `weight:${start.toISOString()}:${value}` }); return }
        if (type === 'HKCategoryTypeIdentifierSleepAnalysis') { const end = parseDate(a.endDate); if (end) sleeps.push({ start_at: start.toISOString(), end_at: end.toISOString(), sleep_type: sleepType(a.value), source: a.sourceName ?? '', external_id: external || `sleep:${start.toISOString()}:${end.toISOString()}:${a.value}` }); return }
        if (type && !type.startsWith('HKQuantityTypeIdentifier') && type !== 'HKCategoryTypeIdentifierSleepAnalysis') warnings++
      } else if (name === 'Workout') { processed++; const start = parseDate(a.startDate); const end = parseDate(a.endDate); if (start && end) workouts.push({ title: a.workoutActivityType ?? 'Entrenamiento Apple Salud', activity_type: 'other', started_at: start.toISOString(), duration_minutes: Math.max(1, Math.round((end.getTime() - start.getTime()) / 60000)), external_id: a.uuid || `workout:${start.toISOString()}:${end.toISOString()}`, notes: a.sourceName ? `Apple Salud · ${a.sourceName}` : 'Apple Salud' }) }
      if (processed % 1000 === 0) onProgress(processed) }
    while (true) { const { value, done } = await reader.read(); if (done) break; buffer += value; if (/<!DOCTYPE|<!ENTITY/i.test(buffer.slice(0, 4096))) throw new Error('El XML contiene entidades o DTD no permitidos.'); let match: RegExpExecArray | null; const re = /<(Record|Workout)\b[^>]*\/?>(?:\s*<\/\1>)?/g; let last = 0; while ((match = re.exec(buffer))) { process(match[0]); last = re.lastIndex }; buffer = buffer.slice(last); if (buffer.length > 100_000) buffer = buffer.slice(-10_000) }
    if (!sawHealthData) throw new Error('El archivo no parece una exportación de Apple Salud.')
    const source = await supabase.from('data_sources').upsert({ user_id: userId, name: 'Apple Salud', source_type: 'external', provider: 'apple_health', metadata: {} }, { onConflict: 'user_id,name' }).select('id').single(); if (source.error || !source.data) throw new Error(source.error?.message ?? 'No se pudo crear la fuente Apple Salud.')
    const summaries = [...daily].map(([summary_date, d]) => ({ user_id: userId, summary_date, steps: Math.round(d.steps), walking_running_distance_km: d.distance, active_energy_kcal: d.activeEnergy, basal_energy_kcal: d.basalEnergy, flights_climbed: d.flights, walking_speed_avg: average(d.walkingSpeed), walking_step_length_avg: average(d.stepLength), walking_asymmetry_avg: average(d.asymmetry), walking_double_support_avg: average(d.doubleSupport), walking_steadiness_avg: average(d.steadiness), is_partial: summary_date === dateKey(new Date()) }))
    if (summaries.length) { const r = await supabase.from('health_daily_summaries').upsert(summaries, { onConflict: 'user_id,summary_date' }); if (r.error) throw new Error(r.error.message) }
    if (weights.length) { const metric = await supabase.from('metrics').upsert({ user_id: userId, slug: 'body_weight', name: 'Peso corporal', pillar: 'health', data_type: 'numeric', unit: 'kg', aggregation: 'latest' }, { onConflict: 'user_id,slug' }).select('id').single(); if (metric.error || !metric.data) throw new Error(metric.error?.message ?? 'No se pudo preparar peso.'); const r = await supabase.from('metric_entries').upsert(weights.map((w) => ({ ...w, user_id: userId, metric_id: metric.data.id, data_source_id: source.data.id, metadata: { provider: 'apple_health' } })), { onConflict: 'user_id,data_source_id,external_id', ignoreDuplicates: true }); if (r.error) throw new Error(r.error.message) }
    if (sleeps.length) { const r = await supabase.from('health_sleep_sessions').upsert(sleeps.map((s) => ({ ...s, user_id: userId })), { onConflict: 'user_id,external_id', ignoreDuplicates: true }); if (r.error) throw new Error(r.error.message) }
    if (workouts.length) { const r = await supabase.from('workouts').upsert(workouts.map((w) => ({ ...w, user_id: userId, source_id: source.data.id, perceived_exertion: null })), { onConflict: 'user_id,source_id,external_id', ignoreDuplicates: true }); if (r.error) throw new Error(r.error.message) }
    const dates = [...daily.keys()].sort(); const result: AppleImportResult = { recordsProcessed: processed, recordsImported: summaries.length + weights.length + sleeps.length + workouts.length, recordsSkipped: skipped, days: summaries.length, weight: weights.length, sleep: sleeps.length, workouts: workouts.length, earliestDate: dates[0] ?? null, latestDate: dates[dates.length - 1] ?? null, warnings }; const finish = await supabase.from('health_imports').update({ status: warnings ? 'completed_with_warnings' : 'completed', finished_at: new Date().toISOString(), records_processed: processed, records_imported: result.recordsImported, records_skipped: skipped, earliest_date: result.earliestDate, latest_date: result.latestDate, summary: result as unknown as Json }).eq('id', importId); if (finish.error) throw new Error(finish.error.message); return result
  } catch (error) { await supabase.from('health_imports').update({ status: 'failed', finished_at: new Date().toISOString(), error_message: error instanceof Error ? error.message : 'Error interno.' }).eq('id', importId); throw error }
}
