import { FileUp, X } from 'lucide-react'
import { useRef, useState, type DragEvent } from 'react'
import { useAuth } from '../auth/AuthProvider'
import { importAppleHealth, type AppleImportResult } from './appleHealthImporter'

export function AppleHealthImportModal({ onClose, onComplete }: { onClose: () => void; onComplete: () => void }) {
  const { user } = useAuth(); const input = useRef<HTMLInputElement>(null); const [file, setFile] = useState<File | null>(null); const [processed, setProcessed] = useState(0); const [running, setRunning] = useState(false); const [result, setResult] = useState<AppleImportResult | null>(null); const [error, setError] = useState('')
  const choose = (candidate?: File) => { setError(''); setResult(null); if (!candidate) return; if (!candidate.name.toLowerCase().endsWith('.xml')) { setError('Seleccioná un archivo .xml exportado por Apple Salud.'); return }; setFile(candidate) }
  const run = async () => { if (!file || !user) return; setRunning(true); setError(''); try { const imported = await importAppleHealth(file, user.id, setProcessed); setResult(imported); onComplete() } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo procesar el archivo.') } finally { setRunning(false) } }
  const drop = (event: DragEvent<HTMLButtonElement>) => { event.preventDefault(); choose(event.dataTransfer.files[0]) }
  return <div className="home-modal-backdrop" role="presentation"><section aria-modal="true" className="home-modal apple-health-modal" role="dialog"><div className="task-form"><div className="task-form-heading"><div><p className="eyebrow">Apple Salud</p><h2>Importar datos</h2></div><button aria-label="Cerrar" className="text-button" disabled={running} onClick={onClose} type="button"><X size={18}/></button></div>{!result && <><p>Podés importar el archivo exportado desde Apple Salud. Momentum procesará actividad, pasos, distancia, energía, peso y otros datos compatibles.</p><button className="apple-health-drop" onClick={() => input.current?.click()} onDragOver={(event) => event.preventDefault()} onDrop={drop} type="button"><FileUp size={25}/><strong>{file ? file.name : 'Arrastrá tu export.xml o seleccioná un archivo'}</strong><small>{file ? `${(file.size / 1024 / 1024).toFixed(1)} MB${file.size > 100 * 1024 * 1024 ? ' · archivo grande' : ''}` : 'Solo archivos .xml'}</small></button><input accept=".xml,application/xml,text/xml" hidden onChange={(event) => choose(event.target.files?.[0])} ref={input} type="file"/>{running && <div className="apple-health-progress"><strong>Procesando Apple Salud…</strong><span>{processed.toLocaleString('es-AR')} registros analizados</span></div>}{error && <p className="form-error">{error}</p>}<div className="task-form-actions"><button className="secondary-button" disabled={running} onClick={onClose} type="button">Cancelar</button><button className="primary-button" disabled={!file || running} onClick={run} type="button">{running ? 'Procesando…' : 'Importar'}</button></div></>}{result && <><div className="apple-health-result"><strong>Importación completada</strong><span>Período: {result.earliestDate ?? '—'} → {result.latestDate ?? '—'}</span><span>Días importados: {result.days.toLocaleString('es-AR')}</span><span>Registros procesados: {result.recordsProcessed.toLocaleString('es-AR')}</span><span>Peso: {result.weight} mediciones · Sueño: {result.sleep} sesiones · Entrenamientos: {result.workouts}</span><span>Duplicados omitidos: {result.recordsSkipped}</span>{result.warnings > 0 && <small>{result.warnings} tipos o registros no compatibles fueron ignorados.</small>}</div><div className="task-form-actions"><button className="primary-button" onClick={onClose} type="button">Listo</button></div></>}</div></section></div>
}
