import { useQuery } from '@tanstack/react-query'
import { supabase } from '../lib/supabase'
import type { Database } from '../types/database'

export type CheckinEntry = Database['public']['Tables']['metric_entries']['Row']
export const checkinDefinitions = [{ slug: 'sleep_duration', name: 'Horas de sueño', unit: 'h', min: 0, max: 24 }, { slug: 'sleep_quality', name: 'Calidad del sueño', unit: '/5', min: 1, max: 5 }, { slug: 'energy_level', name: 'Energía', unit: '/5', min: 1, max: 5 }, { slug: 'fatigue_level', name: 'Fatiga', unit: '/5', min: 1, max: 5 }, { slug: 'mood_level', name: 'Ánimo', unit: '/5', min: 1, max: 5 }] as const
export const dailyCheckinKey = (id: string) => ['daily-checkin', id] as const
export const requireCheckinData = <T,>(result: { data: T | null; error: { message: string } | null }) => { if (result.error) throw new Error(result.error.message); if (result.data === null) throw new Error('Sin respuesta de Supabase.'); return result.data }
export function useDailyCheckinData(userId: string | undefined) { return useQuery({ queryKey: dailyCheckinKey(userId ?? ''), enabled: Boolean(userId), retry: false, queryFn: async () => { const metrics = requireCheckinData(await supabase.from('metrics').select('*').eq('user_id', userId!).in('slug', checkinDefinitions.map((item) => item.slug))); const entries = metrics.length ? requireCheckinData(await supabase.from('metric_entries').select('*').eq('user_id', userId!).in('metric_id', metrics.map((item) => item.id)).not('check_in_date', 'is', null).order('check_in_date', { ascending: false })) : []; return { metrics, entries } } }) }
export function getCheckinSummary(data: { metrics: Database['public']['Tables']['metrics']['Row'][]; entries: CheckinEntry[] }) { const byMetric = new Map(data.metrics.map((metric) => [metric.id, metric.slug])); const latestDate = data.entries[0]?.check_in_date ?? null; const energy = latestDate ? data.entries.find((entry) => entry.check_in_date === latestDate && byMetric.get(entry.metric_id) === 'energy_level')?.numeric_value ?? null : null; const since = new Date(); since.setDate(since.getDate() - 7); const sleep = data.entries.filter((entry) => byMetric.get(entry.metric_id) === 'sleep_duration' && entry.check_in_date && new Date(`${entry.check_in_date}T00:00:00`) >= since).map((entry) => Number(entry.numeric_value)); return { latestDate, energy, weeklySleep: sleep.length ? sleep.reduce((sum, value) => sum + value, 0) / sleep.length : null } }
