import { useMutation, useQueryClient } from '@tanstack/react-query'
import { useState, type FormEvent } from 'react'
import { Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { supabase } from '../lib/supabase'
import { useAuth } from '../auth/AuthProvider'
import type { Json } from '../types/database'
import { checkinDefinitions as definitions, dailyCheckinKey, requireCheckinData as requireData, type CheckinEntry as Entry, useDailyCheckinData } from './dailyCheckinData'

const today = () => new Date().toLocaleDateString('en-CA')
export function DailyCheckin() {
  const { user } = useAuth(); const query = useDailyCheckinData(user?.id); const mutations = useCheckinMutations(user?.id); const [open, setOpen] = useState(false)
  if (query.isLoading) return <section className="content-card"><p>Cargando sueño y bienestar…</p></section>
  if (query.error || !query.data) return <section className="content-card tasks-state tasks-state--error">No se pudo cargar el check-in diario.</section>
  const byMetric = new Map(query.data.metrics.map((metric) => [metric.id, metric])); const latestDate = query.data.entries[0]?.check_in_date; const latest = latestDate ? query.data.entries.filter((entry) => entry.check_in_date === latestDate) : []; const avg = (slug: string, days: number) => { const since = new Date(); since.setDate(since.getDate() - days); const values = query.data.entries.filter((entry) => byMetric.get(entry.metric_id)?.slug === slug && entry.check_in_date && new Date(`${entry.check_in_date}T00:00:00`) >= since).map((entry) => Number(entry.numeric_value)); return values.length ? (values.reduce((a, b) => a + b, 0) / values.length).toFixed(1) : '—' }
  const chart = (slug: string) => query.data.entries.filter((entry) => byMetric.get(entry.metric_id)?.slug === slug).map((entry) => ({ date: entry.check_in_date ?? '', value: Number(entry.numeric_value) })).reverse()
  return <section className="content-card daily-checkin"><div className="section-heading"><div><p className="eyebrow">Sueño y bienestar</p><h2>Check-in diario</h2></div><button className="secondary-button" onClick={() => setOpen(true)} type="button">{latestDate === today() ? 'Editar hoy' : 'Registrar check-in'}</button></div>{open && <CheckinForm initial={latestDate === today() ? latest : []} onCancel={() => setOpen(false)} onSave={async (input) => { await mutations.save.mutateAsync(input); setOpen(false) }} />}{mutations.save.error && <p className="form-error">No se pudo guardar el check-in.</p>}<div className="weight-summary"><Stat label="Último check-in" value={latestDate ?? 'Sin registros'} /><Stat label="Sueño · 7 días" value={`${avg('sleep_duration', 7)} h`} /><Stat label="Sueño · 30 días" value={`${avg('sleep_duration', 30)} h`} /></div><div className="daily-charts"><CheckinChart title="Horas de sueño" data={chart('sleep_duration')} /><CheckinChart title="Nivel de energía" data={chart('energy_level')} /></div><div className="weight-entry-list">{latestDate ? <article className="weight-entry"><div><strong>{latestDate}</strong><p>{latest.map((entry) => `${byMetric.get(entry.metric_id)?.name}: ${entry.numeric_value}${byMetric.get(entry.metric_id)?.unit}`).join(' · ')}</p></div></article> : <div className="tasks-state">Todavía no hay check-ins.</div>}</div></section>
}
function CheckinChart({ title, data }: { title: string; data: { date: string; value: number }[] }) { return <div className="chart-card"><h3>{title}</h3>{data.length ? <div className="chart-area"><ResponsiveContainer height="100%" width="100%"><LineChart data={data}><XAxis dataKey="date" /><YAxis /><Tooltip /><Line dataKey="value" stroke="#3b82f6" /></LineChart></ResponsiveContainer></div> : <div className="chart-empty">Sin datos</div>}</div> }
function Stat({ label, value }: { label: string; value: string }) { return <article className="weight-stat"><p>{label}</p><strong>{value}</strong></article> }
function CheckinForm({ initial, onCancel, onSave }: { initial: Entry[]; onCancel: () => void; onSave: (input: { date: string; values: Record<string, string>; note: string }) => Promise<void> }) { const [date, setDate] = useState(initial[0]?.check_in_date ?? today()); const [values, setValues] = useState<Record<string, string>>(() => Object.fromEntries(definitions.map((item) => [item.slug, initial.find((entry) => entry.metadata && typeof entry.metadata === 'object' && !Array.isArray(entry.metadata) && entry.metadata.slug === item.slug)?.numeric_value?.toString() ?? '']))); const [note, setNote] = useState(''); const [error, setError] = useState(''); const submit = async (event: FormEvent) => { event.preventDefault(); for (const item of definitions) { const value = Number(values[item.slug]); if (!Number.isFinite(value) || value < item.min || value > item.max) { setError(`${item.name} debe estar entre ${item.min} y ${item.max}.`); return } } await onSave({ date, values, note }); }; return <form className="task-form" onSubmit={submit}><label>Fecha<input onChange={(e) => setDate(e.target.value)} required type="date" value={date} /></label><div className="task-form-grid">{definitions.map((item) => <label key={item.slug}>{item.name} ({item.unit})<input max={item.max} min={item.min} onChange={(e) => setValues({ ...values, [item.slug]: e.target.value })} required step={item.slug === 'sleep_duration' ? '0.1' : '1'} type="number" value={values[item.slug]} /></label>)}</div><label>Nota opcional<textarea onChange={(e) => setNote(e.target.value)} value={note} /></label>{error && <p className="form-error">{error}</p>}<div className="task-form-actions"><button className="secondary-button" onClick={onCancel} type="button">Cancelar</button><button className="primary-button" type="submit">Guardar check-in</button></div></form> }
function useCheckinMutations(userId: string | undefined) { const client = useQueryClient(); return { save: useMutation({ retry: false, mutationFn: async ({ date, values, note }: { date: string; values: Record<string, string>; note: string }) => { const metricRows = await supabase.from('metrics').upsert(definitions.map((item) => ({ user_id: userId!, slug: item.slug, name: item.name, pillar: 'health', data_type: 'numeric', unit: item.unit, aggregation: 'latest' })), { onConflict: 'user_id,slug', ignoreDuplicates: true }).select(); if (metricRows.error) throw new Error(metricRows.error.message); const metrics = requireData(await supabase.from('metrics').select('*').eq('user_id', userId!).in('slug', definitions.map((item) => item.slug))); const sourceResult = await supabase.from('data_sources').select('id').eq('user_id', userId!).eq('source_type', 'manual').maybeSingle(); const sourceId = sourceResult.data?.id; if (sourceResult.error) throw new Error(sourceResult.error.message); if (!sourceId) throw new Error('No se encontró la fuente manual.'); const entries = metrics.map((metric) => ({ user_id: userId!, metric_id: metric.id, data_source_id: sourceId, numeric_value: Number(values[metric.slug!]), recorded_at: new Date(`${date}T12:00:00`).toISOString(), check_in_date: date, metadata: { slug: metric.slug, note } as Json })); const result = await supabase.from('metric_entries').upsert(entries, { onConflict: 'user_id,metric_id,check_in_date' }); if (result.error) throw new Error(result.error.message) }, onSuccess: async () => { if (userId) await client.invalidateQueries({ queryKey: dailyCheckinKey(userId) }) } }) } }
