import { Flag, Pencil, Plus, Trash2 } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { useAuth } from '../auth/AuthProvider'
import { useWeightData } from './weight'
import { useWorkouts, workoutSummary } from './workoutData'
import { goalProgress, type Goal, type GoalInput, useGoalMutations, useGoals } from './goalData'
const types=['reach_value','reduce_value','increase_value','weekly_frequency','weekly_duration']
export function Goals(){const {user}=useAuth();const goals=useGoals(user?.id);const mutations=useGoalMutations(user?.id);const weight=useWeightData(user?.id);const workouts=useWorkouts(user?.id);const [open,setOpen]=useState(false);const [editing,setEditing]=useState<Goal>();if(goals.isLoading)return <section className="content-card">Cargando objetivos…</section>;if(goals.error)return <section className="content-card tasks-state tasks-state--error">No se pudieron cargar los objetivos.</section>;const list=goals.data??[];const current=(goal:Goal)=>goal.target_type==='weekly_frequency'?workoutSummary(workouts.data??[]).count:goal.target_type==='weekly_duration'?workoutSummary(workouts.data??[]).minutes:weight.data?.entries[0]?.numeric_value??null;return <section className="content-card"><div className="section-heading"><div><p className="eyebrow">Dirección</p><h2>Objetivos de salud</h2></div><button className="secondary-button" onClick={()=>setOpen(true)} type="button"><Plus size={16}/>Nuevo objetivo</button></div>{(open||editing)&&<GoalForm goal={editing} onCancel={()=>{setOpen(false);setEditing(undefined)}} onSave={async input=>{if(editing)await mutations.update.mutateAsync({id:editing.id,input});else await mutations.create.mutateAsync(input);setOpen(false);setEditing(undefined)}}/>}{list.length?<div className="weight-entry-list">{list.map(goal=>{const progress=goalProgress(goal,current(goal));return <article className="weight-entry" key={goal.id}><div><strong>{goal.title}</strong><p>{goal.status} · {progress===null?'Sin datos suficientes':`${progress.toFixed(0)}%`}</p>{progress!==null&&<span className="mini-progress"><i style={{width:`${progress}%`}}/></span>}</div><div className="task-actions"><button aria-label="Editar objetivo" onClick={()=>setEditing(goal)} type="button"><Pencil size={16}/></button>{goal.status==='active'&&<button aria-label="Pausar objetivo" onClick={()=>mutations.status.mutate({id:goal.id,status:'paused'})} type="button">Ⅱ</button>}{goal.status!=='completed'&&<button aria-label="Completar objetivo" onClick={()=>mutations.status.mutate({id:goal.id,status:'completed'})} type="button">✓</button>}<button aria-label="Eliminar objetivo" onClick={()=>{if(window.confirm('¿Eliminar este objetivo?'))mutations.remove.mutate(goal.id)}} type="button"><Trash2 size={16}/></button></div></article>})}</div>:<div className="tasks-state"><Flag size={20}/> Todavía no hay objetivos activos.</div>}</section>}
function GoalForm({goal,onCancel,onSave}:{goal?:Goal;onCancel:()=>void;onSave:(input:GoalInput)=>Promise<void>}){const [title,setTitle]=useState(goal?.title??'');const [type,setType]=useState(goal?.target_type??'reach_value');const [target,setTarget]=useState(goal?.target_value?.toString()??'');const submit=async(e:FormEvent)=>{e.preventDefault();const value=Number(target);if(!title.trim()||!Number.isFinite(value)||value<0)return;await onSave({title:title.trim(),description:null,metric_id:null,target_type:type,target_value:value,start_value:goal?.start_value??null,start_date:goal?.start_date??new Date().toLocaleDateString('en-CA'),due_date:null})};return <form className="task-form" onSubmit={submit}><label>Título<input onChange={e=>setTitle(e.target.value)} required value={title}/></label><div className="task-form-grid"><label>Tipo<select onChange={e=>setType(e.target.value)} value={type}>{types.map(x=><option key={x}>{x}</option>)}</select></label><label>Objetivo<input min="0" onChange={e=>setTarget(e.target.value)} required type="number" value={target}/></label></div><div className="task-form-actions"><button className="secondary-button" onClick={onCancel} type="button">Cancelar</button><button className="primary-button" type="submit">Guardar</button></div></form>}
