import { Activity, Droplets, Dumbbell, Footprints, HeartPulse, Moon, Scale, TrendingUp, Zap } from 'lucide-react'
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { useState, type CSSProperties, type FormEvent, type ReactNode } from 'react'
import { useLocation } from 'react-router-dom'
import { useAuth } from '../auth/AuthProvider'
import { DailyCheckin } from './DailyCheckin'
import { Goals } from './Goals'
import { Workouts } from './Workouts'
import { healthToday, settingsFor, useDailyMetricMutation, useHealthDashboard, type HealthDashboardData, type MetricEntry } from './dashboardData'
import { WeightPage } from './WeightPage'

type Period = 30 | 90
type Slug = 'body_weight' | 'sleep_duration' | 'sleep_quality' | 'energy_level' | 'fatigue_level' | 'water_ml' | 'steps'
const number = (entry: MetricEntry | undefined) => entry?.numeric_value === null || entry?.numeric_value === undefined ? null : Number(entry.numeric_value)
const dateKey = (value: string) => new Date(value).toLocaleDateString('en-CA')
const since = (days: number) => { const date = new Date(); date.setDate(date.getDate() - days); return date }

function entriesFor(data: HealthDashboardData, slug: Slug) { const metric = data.metrics.find((item) => item.slug === slug); return metric ? data.entries.filter((item) => item.metric_id === metric.id) : [] }
function latest(data: HealthDashboardData, slug: Slug) { return entriesFor(data, slug)[0] }
function latestCheckin(data: HealthDashboardData, slug: Slug) { return entriesFor(data, slug).find((item) => item.check_in_date) }
function weeklyWorkouts(data: HealthDashboardData) { return data.workouts.filter((item) => new Date(item.started_at) >= since(7)) }
function exerciseDays(data: HealthDashboardData) { return new Set(data.workouts.map((item) => dateKey(item.started_at))) }

export function HealthDashboard() {
  const { user } = useAuth(); const location = useLocation(); const requestedAction = (location.state as { openAction?: string } | null)?.openAction; const [period, setPeriod] = useState<Period>(30); const [weightSignal, setWeightSignal] = useState(() => requestedAction === 'weight' ? 1 : 0); const [workoutSignal, setWorkoutSignal] = useState(() => requestedAction === 'workout' ? 1 : 0); const [checkinSignal, setCheckinSignal] = useState(0); const [historyOpen, setHistoryOpen] = useState(() => requestedAction === 'weight'); const query = useHealthDashboard(user?.id, period); const metricMutation = useDailyMetricMutation(user?.id)
  if (query.isLoading) return <main className="page"><div className="tasks-state">Cargando tu dashboard de Salud…</div></main>
  if (query.error || !query.data) return <main className="page"><div className="tasks-state tasks-state--error">No se pudo cargar Salud. Intentá de nuevo.</div></main>
  const data = query.data; const settings = settingsFor(data); const weight = latest(data, 'body_weight'); const weightEntries = entriesFor(data, 'body_weight'); const previous = weightEntries[1]; const weightDelta = number(weight) !== null && number(previous) !== null ? number(weight)! - number(previous)! : null
  const sleep = latestCheckin(data, 'sleep_duration'); const energy = latestCheckin(data, 'energy_level'); const water = latest(data, 'water_ml'); const steps = latest(data, 'steps'); const trainings = weeklyWorkouts(data)
  return <main className="page health-dashboard">
    <header className="page-header"><div><p className="eyebrow">Pilar personal</p><h1>Salud</h1><p className="page-description">Una vista clara de tu estado, entrenamiento y recuperación.</p></div><PeriodSelector period={period} onChange={setPeriod} /></header>
    <nav aria-label="Secciones de Salud" className="health-nav"><a href="#estado-actual">Estado actual</a><a href="#tendencias">Tendencias</a><a href="#entrenamiento">Entrenamiento</a><a href="#recuperacion">Recuperación</a></nav>
    <section id="estado-actual"><div className="section-heading"><div><p className="eyebrow">Hoy</p><h2>Estado actual</h2></div></div><div className="health-kpi-grid">
      <Kpi action={() => { setHistoryOpen(true); setWeightSignal((value) => value + 1); setTimeout(() => document.getElementById('historial')?.scrollIntoView({ behavior: 'smooth' }), 0) }} icon={<Scale size={19}/>} label="Último peso" value={weight ? `${number(weight)} kg` : 'Sin registro'} detail={weightDelta === null ? 'Registrá una medición' : `${weightDelta > 0 ? '+' : ''}${weightDelta.toFixed(1)} kg vs. anterior`} tone="blue" />
      <Kpi action={() => { setWorkoutSignal((value) => value + 1); document.getElementById('entrenamiento')?.scrollIntoView({ behavior: 'smooth' }) }} icon={<Dumbbell size={19}/>} label="Entrenamiento" value={`${trainings.length} esta semana`} detail={trainings.length ? `${trainings.reduce((sum, item) => sum + item.duration_minutes, 0)} min acumulados` : 'Sin sesiones recientes'} tone="violet" />
      <Kpi action={() => { setCheckinSignal((value) => value + 1); document.getElementById('recuperacion')?.scrollIntoView({ behavior: 'smooth' }) }} icon={<Moon size={19}/>} label="Sueño de anoche" value={sleep ? `${number(sleep)} h` : 'Sin check-in'} detail={sleep?.check_in_date ?? 'Registrá tu descanso'} tone="sky" />
      <Kpi action={() => { setCheckinSignal((value) => value + 1); document.getElementById('recuperacion')?.scrollIntoView({ behavior: 'smooth' }) }} icon={<Zap size={19}/>} label="Energía" value={energy ? `${number(energy)}/5` : 'Sin check-in'} detail={energy?.check_in_date ?? 'Registrá cómo te sentís'} tone="amber" />
      <QuickMetric icon={<Droplets size={19}/>} label="Agua" value={number(water)} goal={settings.water_goal_ml} unit="ml" onSave={(value) => metricMutation.mutateAsync({ slug: 'water_ml', value })} saving={metricMutation.isPending} />
      <QuickMetric icon={<Footprints size={19}/>} label="Pasos" value={number(steps)} goal={settings.steps_goal} unit="pasos" onSave={(value) => metricMutation.mutateAsync({ slug: 'steps', value })} saving={metricMutation.isPending} />
    </div></section>
    <section className="health-section" id="tendencias"><div className="section-heading"><div><p className="eyebrow">Evolución</p><h2>Tendencias</h2></div><span className="section-status">Últimos {period} días</span></div><div className="health-chart-grid"><TrendCard title="Peso" empty="Registrá una medición de peso." data={weightEntries.map((item) => ({ date: item.recorded_at, value: number(item) ?? 0 })).reverse()} unit="kg"/><TrendCard title="Sueño y energía" empty="Completá un check-in diario." data={mergeByDate(entriesFor(data, 'sleep_duration'), entriesFor(data, 'energy_level'))} unit="" multi/><MinutesCard workouts={data.workouts}/><Heatmap data={data}/><CompletionRings data={data}/></div></section>
    <section className="health-section" id="entrenamiento"><div className="section-heading"><div><p className="eyebrow">Movimiento</p><h2>Entrenamiento</h2></div></div><TrainingOverview workouts={data.workouts}/><Workouts key={workoutSignal} openSignal={workoutSignal} /></section>
    <section className="health-section" id="recuperacion"><div className="section-heading"><div><p className="eyebrow">Carga y descanso</p><h2>Recuperación</h2></div></div><RecoveryPanel data={data} enabled={settings.show_readiness}/><DailyCheckin key={checkinSignal} openSignal={checkinSignal} /></section>
    <section className="health-section health-history" id="historial"><details onToggle={(event) => setHistoryOpen(event.currentTarget.open)} open={historyOpen}><summary>Historial y objetivos</summary><WeightPage embedded key={weightSignal} openSignal={weightSignal} /><Goals /></details></section>
  </main>
}

function Kpi({ icon, label, value, detail, tone, action }: { icon: ReactNode; label: string; value: string; detail: string; tone: string; action?: () => void }) { return <article className={`health-kpi health-kpi--${tone}`}><span className="health-kpi-icon">{icon}</span><p>{label}</p><strong>{value}</strong><small>{detail}</small>{action && <button className="text-button health-kpi-action" onClick={action} type="button">Registrar</button>}</article> }
function QuickMetric({ icon, label, value, goal, unit, onSave, saving }: { icon: ReactNode; label: string; value: number | null; goal: number; unit: string; onSave: (value: number) => Promise<unknown>; saving: boolean }) { const [open, setOpen] = useState(false); const [input, setInput] = useState(value?.toString() ?? ''); const submit = async (event: FormEvent) => { event.preventDefault(); const next = Number(input); if (!Number.isFinite(next) || next < 0) return; await onSave(next); setOpen(false) }; const percent = Math.min(100, Math.round(((value ?? 0) / goal) * 100)); return <article className="health-kpi health-kpi--teal"><span className="health-kpi-icon">{icon}</span><p>{label}</p><strong>{value === null ? 'Sin registro' : `${value.toLocaleString('es-AR')} ${unit}`}</strong><small>{value === null ? `Meta: ${goal.toLocaleString('es-AR')} ${unit}` : `${percent}% de ${goal.toLocaleString('es-AR')} ${unit}`}</small><button className="text-button health-kpi-action" onClick={() => setOpen(!open)} type="button">{value === null ? 'Registrar' : 'Editar'}</button>{open && <form className="quick-metric-form" onSubmit={submit}><input aria-label={label} autoFocus min="0" onChange={(event) => setInput(event.target.value)} required type="number" value={input}/><button disabled={saving} type="submit">Guardar</button></form>}</article> }
function PeriodSelector({ period, onChange }: { period: Period; onChange: (period: Period) => void }) { return <div className="period-selector">{([30, 90] as const).map((value) => <button className={period === value ? 'active' : ''} key={value} onClick={() => onChange(value)} type="button">{value} días</button>)}</div> }
function TrendCard({ title, empty, data, unit, multi = false }: { title: string; empty: string; data: Array<{ date: string; value: number; energy?: number }>; unit: string; multi?: boolean }) { const chart = data.map((item) => ({ ...item, date: new Intl.DateTimeFormat('es-AR', { day: '2-digit', month: 'short' }).format(new Date(item.date)) })); return <article className="chart-card"><h3>{title}{unit ? ` (${unit})` : ''}</h3>{chart.length ? <div className="chart-area"><ResponsiveContainer height="100%" width="100%"><LineChart data={chart}><CartesianGrid stroke="#26364d" strokeDasharray="3 3" vertical={false}/><XAxis dataKey="date" tick={{ fill:'#94a3b8', fontSize:11 }}/><YAxis tick={{ fill:'#94a3b8', fontSize:11 }}/><Tooltip/><Line dataKey="value" dot={false} name={multi ? 'Sueño' : title} stroke="#60a5fa" strokeWidth={3} type="monotone"/>{multi && <Line dataKey="energy" dot={false} name="Energía" stroke="#fbbf24" strokeWidth={3} type="monotone"/>}</LineChart></ResponsiveContainer></div> : <div className="chart-empty">{empty}</div>}</article> }
function MinutesCard({ workouts }: { workouts: HealthDashboardData['workouts'] }) { const points = Array.from({ length: 6 }, (_, index) => { const end = new Date(); end.setDate(end.getDate() - index * 7); const start = new Date(end); start.setDate(end.getDate() - 6); return { label: `${start.getDate()}/${start.getMonth() + 1}`, minutes: workouts.filter((item) => new Date(item.started_at) >= start && new Date(item.started_at) <= end).reduce((sum, item) => sum + item.duration_minutes, 0) } }).reverse(); return <article className="chart-card"><h3>Minutos entrenados</h3><div className="chart-area"><ResponsiveContainer height="100%" width="100%"><BarChart data={points}><XAxis dataKey="label" tick={{ fill:'#94a3b8', fontSize:11 }}/><YAxis tick={{ fill:'#94a3b8', fontSize:11 }}/><Tooltip/><Bar dataKey="minutes" fill="#8b5cf6" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></article> }
function Heatmap({ data }: { data: HealthDashboardData }) { const days = Array.from({ length: 28 }, (_, index) => { const date = new Date(); date.setDate(date.getDate() - (27 - index)); const key = date.toLocaleDateString('en-CA'); const count = ['body_weight','sleep_duration','water_ml','steps'].filter((slug) => entriesFor(data, slug as Slug).some((entry) => (entry.check_in_date ?? dateKey(entry.recorded_at)) === key)).length + (exerciseDays(data).has(key) ? 1 : 0); return { key, count } }); return <article className="chart-card"><h3>Actividad mensual</h3><div className="health-heatmap">{days.map((day) => <i aria-label={`${day.key}: ${day.count} registros`} className={`health-heatmap-level-${Math.min(day.count, 4)}`} key={day.key} title={`${day.key}: ${day.count} registros`}/>)}</div><small>Registros de Salud por día</small></article> }
function CompletionRings({ data }: { data: HealthDashboardData }) { const today = healthToday(); const have = (slug: Slug) => entriesFor(data, slug).some((entry) => (entry.check_in_date ?? dateKey(entry.recorded_at)) === today); const counts = [{ label:'Bienestar', value:['sleep_duration','energy_level','fatigue_level'].filter((slug) => have(slug as Slug)).length, total:3 }, { label:'Movimiento', value:exerciseDays(data).has(today) ? 1 : 0, total:1 }, { label:'Diario', value:['water_ml','steps'].filter((slug) => have(slug as Slug)).length, total:2 }]; return <article className="chart-card"><h3>Completitud de hoy</h3><div className="completion-rings">{counts.map((item) => <div key={item.label}><span style={{ '--completion': `${(item.value / item.total) * 100}%` } as CSSProperties}>{item.value}/{item.total}</span><small>{item.label}</small></div>)}</div></article> }
function TrainingOverview({ workouts }: { workouts: HealthDashboardData['workouts'] }) { const current = workouts.filter((item) => new Date(item.started_at) >= since(7)); const rpe = current.filter((item) => item.perceived_exertion !== null); const rest = workouts.length ? Math.floor((new Date().getTime() - new Date(workouts[0].started_at).getTime()) / 86_400_000) : null; return <div className="health-training-summary"><Kpi icon={<Dumbbell size={19}/>} label="Volumen semanal" value="Sin series" detail="Agregá ejercicios y series para calcularlo" tone="violet"/><Kpi icon={<Activity size={19}/>} label="RPE semanal" value={rpe.length ? (rpe.reduce((sum, item) => sum + item.perceived_exertion!, 0) / rpe.length).toFixed(1) : 'Sin datos'} detail={`${current.length} sesiones`} tone="amber"/><Kpi icon={<TrendingUp size={19}/>} label="Récords personales" value="Sin series" detail="Se calcularán desde peso y repeticiones" tone="blue"/><Kpi icon={<HeartPulse size={19}/>} label="Descanso" value={rest === null ? 'Sin datos' : `${rest} días`} detail="Desde tu última sesión" tone="teal"/></div> }
function RecoveryPanel({ data, enabled }: { data: HealthDashboardData; enabled: boolean }) { const sleep = number(latestCheckin(data, 'sleep_duration')); const quality = number(latestCheckin(data, 'sleep_quality')); const energy = number(latestCheckin(data, 'energy_level')); const fatigue = number(latestCheckin(data, 'fatigue_level')); const enough = [sleep, quality, energy, fatigue].every((value) => value !== null); const score = enough ? Math.round(Math.min(100, (sleep! / 8) * 100) * .3 + ((quality! - 1) / 4 * 100) * .25 + ((energy! - 1) / 4 * 100) * .25 + ((5 - fatigue!) / 4 * 100) * .2) : null; const workouts = weeklyWorkouts(data); return <article className="recovery-panel"><div><h3>Balance entrenamiento y descanso</h3><p>{workouts.length ? `${workouts.length} sesiones y ${workouts.reduce((sum, item) => sum + item.duration_minutes, 0)} minutos en los últimos 7 días.` : 'No hay sesiones registradas esta semana.'}</p></div>{enabled && score !== null ? <div className="readiness-score"><strong>{score}</strong><span>Readiness</span></div> : <div className="readiness-unavailable">{enabled ? 'Completá sueño, calidad, energía y fatiga para calcularlo.' : 'Readiness desactivado.'}</div>}<details className="readiness-details"><summary>Cómo se calcula</summary><p>30% duración de sueño, 25% calidad de sueño, 25% energía y 20% fatiga invertida. Es un indicador personal transparente, no médico.</p></details></article> }
function mergeByDate(sleep: MetricEntry[], energy: MetricEntry[]) { const points = new Map<string, { date: string; value: number; energy?: number }>(); sleep.forEach((item) => points.set(item.check_in_date ?? dateKey(item.recorded_at), { date: item.recorded_at, value: number(item) ?? 0 })); energy.forEach((item) => { const key = item.check_in_date ?? dateKey(item.recorded_at); const current = points.get(key); if (current) current.energy = number(item) ?? 0; else points.set(key, { date: item.recorded_at, value: 0, energy: number(item) ?? 0 }) }); return [...points.values()].sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime()) }
