import { Line, LineChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { CalendarDays, Edit3, Plus, Scale, Trash2, X } from 'lucide-react'
import { useMemo, useState, type FormEvent, type ReactNode } from 'react'
import { useAuth } from '../auth/AuthProvider'
import { noteFromEntry, useWeightData, useWeightMutations, weightDifference, type WeightEntry, type WeightInput } from './weight'
import { DailyCheckin } from './DailyCheckin'
import { Workouts } from './Workouts'
import { Goals } from './Goals'
type Period = '30' | '90' | 'all'; type FormState = { value: string; recordedAt: string; note: string }
const localNow = () => new Date(Date.now() - new Date().getTimezoneOffset() * 60000).toISOString().slice(0, 16)
const localInput = (value: string) => { const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16) }
const displayDate = (value: string) => new Intl.DateTimeFormat('es-AR', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value))
const initialForm = (entry?: WeightEntry): FormState => ({ value: entry?.numeric_value?.toString() ?? '', recordedAt: entry ? localInput(entry.recorded_at) : localNow(), note: entry ? noteFromEntry(entry) : '' })

export function WeightPage({ embedded = false, openSignal = 0 }: { embedded?: boolean; openSignal?: number }) {
  const { user } = useAuth(); const { data, isLoading, error } = useWeightData(user?.id); const mutations = useWeightMutations(user?.id)
  const [period, setPeriod] = useState<Period>('30'); const [creating, setCreating] = useState(openSignal > 0); const [editing, setEditing] = useState<WeightEntry | null>(null)
  if (isLoading) return <div className={embedded ? '' : 'page'}><div className="tasks-state">Cargando tus registros de peso…</div></div>
  if (error || !data) return <div className={embedded ? '' : 'page'}><div className="tasks-state tasks-state--error">No se pudo cargar el peso. {error instanceof Error ? error.message : 'Intentá de nuevo.'}</div></div>
  const difference = weightDifference(data.entries); const visible = filterPeriod(data.entries, period)
  return <div className={embedded ? 'health-weight-embedded' : 'page health-page'}>{embedded ? <div className="section-heading"><div><p className="eyebrow">Registros</p><h2>Peso corporal</h2></div><button className="primary-button" onClick={() => setCreating(true)} type="button"><Plus size={18} />Registrar peso</button></div> : <header className="page-header"><div><p className="eyebrow">Pilar personal</p><h1>Salud</h1><p className="page-description">Registrá y seguí la evolución de tu peso corporal.</p></div><button className="primary-button" onClick={() => setCreating(true)} type="button"><Plus size={18} />Registrar peso</button></header>}
    {(creating || editing) && <WeightForm entry={editing ?? undefined} onCancel={() => { setCreating(false); setEditing(null) }} onSubmit={async (input) => { if (editing) await mutations.update.mutateAsync({ id: editing.id, input }); else { const metric = data.metric ?? await mutations.initialize.mutateAsync(); if (!metric) throw new Error('No se pudo inicializar la métrica de peso.'); await mutations.create.mutateAsync({ metricId: metric.id, input }) } setCreating(false); setEditing(null) }} />}
    {mutations.initialize.error || mutations.create.error || mutations.update.error || mutations.remove.error ? <div className="tasks-state tasks-state--error">No se pudo guardar el cambio. Intentá de nuevo.</div> : null}
    <section className="weight-summary"><Stat icon={<Scale size={20} />} label="Último peso" value={data.entries[0] ? `${data.entries[0].numeric_value} kg` : '—'} /><Stat icon={<CalendarDays size={20} />} label="Último registro" value={data.entries[0] ? displayDate(data.entries[0].recorded_at) : 'Sin registros'} /><Stat icon={<Scale size={20} />} label="Respecto al anterior" value={formatDifference(difference)} /></section>
    <section className="content-card weight-chart-card"><div className="section-heading"><div><p className="eyebrow">Evolución</p><h2>Peso corporal</h2></div><PeriodSelector period={period} setPeriod={setPeriod} /></div>{visible.length === 0 ? <div className="tasks-state">No hay mediciones en este período.</div> : <WeightChart entries={visible} />}</section>
    <section className="content-card weight-history"><div className="section-heading"><div><p className="eyebrow">Registros</p><h2>Historial</h2></div><span className="section-status">{data.entries.length} {data.entries.length === 1 ? 'medición' : 'mediciones'}</span></div>{data.entries.length === 0 ? <div className="tasks-state">Todavía no registraste tu peso. Usá “Registrar peso” para empezar.</div> : <div className="weight-entry-list">{data.entries.map((entry) => <article className="weight-entry" key={entry.id}><div><strong>{entry.numeric_value} kg</strong><time>{displayDate(entry.recorded_at)}</time>{noteFromEntry(entry) && <p>{noteFromEntry(entry)}</p>}</div><div className="task-actions"><button aria-label="Editar medición" onClick={() => setEditing(entry)} type="button"><Edit3 size={16} /></button><button aria-label="Eliminar medición" onClick={() => { if (window.confirm('¿Eliminar esta medición de peso?')) mutations.remove.mutate(entry.id) }} type="button"><Trash2 size={16} /></button></div></article>)}</div>}</section><DailyCheckin /><Workouts /><Goals /></div>
}
function Stat({ icon, label, value }: { icon: ReactNode; label: string; value: string }) { return <article className="weight-stat"><span>{icon}</span><p>{label}</p><strong>{value}</strong></article> }
function WeightForm({ entry, onCancel, onSubmit }: { entry?: WeightEntry; onCancel: () => void; onSubmit: (input: WeightInput) => Promise<void> }) { const [form, setForm] = useState(() => initialForm(entry)); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const value = Number(form.value); const date = new Date(form.recordedAt); if (!Number.isFinite(value) || value < 20 || value > 500) { setMessage('Ingresá un peso razonable entre 20 y 500 kg.'); return }; if (!form.recordedAt || Number.isNaN(date.getTime())) { setMessage('Ingresá una fecha y hora válidas.'); return }; if (date.getTime() > Date.now() + 60000) { setMessage('La fecha de la medición no puede estar en el futuro.'); return }; setSaving(true); setMessage(''); try { await onSubmit({ value, recordedAt: date.toISOString(), note: form.note.trim() }) } catch { setMessage('No se pudo guardar la medición. Intentá de nuevo.') } finally { setSaving(false) } }; return <form className="task-form weight-form" onSubmit={submit}><div className="task-form-heading"><h2>{entry ? 'Editar medición' : 'Registrar peso'}</h2><button aria-label="Cerrar formulario" onClick={onCancel} type="button"><X size={18} /></button></div><div className="task-form-grid"><label>Peso (kg)<input autoFocus min="20" max="500" onChange={(event) => setForm({ ...form, value: event.target.value })} required step="0.1" type="number" value={form.value} /></label><label>Fecha y hora<input onChange={(event) => setForm({ ...form, recordedAt: event.target.value })} required type="datetime-local" value={form.recordedAt} /></label></div><label>Nota opcional<textarea maxLength={500} onChange={(event) => setForm({ ...form, note: event.target.value })} value={form.note} /></label>{message && <p className="form-error" role="alert">{message}</p>}<div className="task-form-actions"><button className="secondary-button" onClick={onCancel} type="button">Cancelar</button><button className="primary-button" disabled={saving} type="submit">{saving ? 'Guardando…' : 'Guardar medición'}</button></div></form> }
function filterPeriod(entries: WeightEntry[], period: Period) { if (period === 'all') return entries; const since = new Date(); since.setDate(since.getDate() - Number(period)); return entries.filter((entry) => new Date(entry.recorded_at) >= since) }
function formatDifference(value: number | null) { if (value === null) return 'Sin comparación'; if (value === 0) return 'Sin cambios'; return `${value > 0 ? '+' : ''}${value.toFixed(1)} kg` }
function PeriodSelector({ period, setPeriod }: { period: Period; setPeriod: (period: Period) => void }) { return <div className="period-selector">{([{ value: '30', label: '30 días' }, { value: '90', label: '90 días' }, { value: 'all', label: 'Todo' }] as const).map((item) => <button className={period === item.value ? 'active' : ''} key={item.value} onClick={() => setPeriod(item.value)} type="button">{item.label}</button>)}</div> }
function WeightChart({ entries }: { entries: WeightEntry[] }) { const data = useMemo(() => [...entries].reverse().map((entry) => ({ date: new Intl.DateTimeFormat('es-AR', { day: '2-digit', month: 'short' }).format(new Date(entry.recorded_at)), value: Number(entry.numeric_value) })), [entries]); return <div className="weight-chart"><ResponsiveContainer height="100%" width="100%"><LineChart data={data}><CartesianGrid stroke="#26364d" strokeDasharray="3 3" vertical={false} /><XAxis axisLine={false} dataKey="date" tick={{ fill: '#94a3b8', fontSize: 12 }} tickLine={false} /><YAxis axisLine={false} domain={['dataMin - 1', 'dataMax + 1']} tick={{ fill: '#94a3b8', fontSize: 12 }} tickLine={false} width={38} /><Tooltip /><Line dataKey="value" dot={{ fill: '#3b82f6', r: 4 }} stroke="#3b82f6" strokeWidth={3} type="monotone" /></LineChart></ResponsiveContainer></div> }
