import { Dumbbell, Pencil, Plus, Trash2, X } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { Bar, BarChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { useAuth } from '../auth/AuthProvider'
import { WorkoutImportModal } from './WorkoutImportModal'
import { workoutSummary, type Workout, type WorkoutInput, useWorkoutMutations, useWorkouts } from './workoutData'
import './workouts.css'
import { useUndoToast } from '../quick-actions/QuickActions'

const types = ['crossfit', 'strength', 'running', 'walking', 'cycling', 'mobility', 'sport', 'other']
const typeLabels: Record<string, string> = { crossfit: 'CrossFit', strength: 'Fuerza', running: 'Correr', walking: 'Caminar', cycling: 'Ciclismo', mobility: 'Movilidad', sport: 'Deporte', other: 'Otro' }
const localNow = () => new Date(Date.now() - new Date().getTimezoneOffset() * 60000).toISOString().slice(0, 16)
const formFor = (workout?: Workout) => ({ title: workout?.title ?? 'Fuerza', activity: workout?.activity_type ?? 'strength', started: workout ? new Date(new Date(workout.started_at).getTime() - new Date(workout.started_at).getTimezoneOffset() * 60000).toISOString().slice(0, 16) : localNow(), duration: workout?.duration_minutes.toString() ?? '45', rpe: workout?.perceived_exertion?.toString() ?? '', notes: workout?.notes ?? '' })
const inputFor = (workout: Workout, rpe = workout.perceived_exertion): WorkoutInput => ({ title: workout.title, activity_type: workout.activity_type, started_at: workout.started_at, duration_minutes: workout.duration_minutes, perceived_exertion: rpe, notes: workout.notes })

export function Workouts({ openSignal = 0 }: { openSignal?: number }) {
  const { user } = useAuth(); const query = useWorkouts(user?.id); const mutations = useWorkoutMutations(user?.id); const [editing, setEditing] = useState<Workout>(); const [open, setOpen] = useState(openSignal > 0); const [importOpen, setImportOpen] = useState(false); const [showAll, setShowAll] = useState(false); const [savingRpe, setSavingRpe] = useState<string | null>(null); const [rpeOverrides, setRpeOverrides] = useState<Record<string, number | null>>({}); const { notify } = useUndoToast()
  if (query.isLoading) return <section className="content-card">Cargando entrenamientos…</section>
  if (query.error) return <section className="content-card tasks-state tasks-state--error">No se pudieron cargar los entrenamientos.</section>
  const items = query.data ?? []; const summary = workoutSummary(items); const visible = showAll ? items : items.slice(0, 5)
  const weeks = Object.values(items.reduce<Record<string, { week: string; minutes: number }>>((result, item) => { const date = new Date(item.started_at); const monday = new Date(date); monday.setDate(date.getDate() - ((date.getDay() + 6) % 7)); const week = monday.toLocaleDateString('es-AR', { day: '2-digit', month: 'short' }); result[week] ??= { week, minutes: 0 }; result[week].minutes += item.duration_minutes; return result }, {})).reverse()
  const saveRpe = async (workout: Workout, rpe: number | null) => { setRpeOverrides((current) => ({ ...current, [workout.id]: rpe })); setSavingRpe(workout.id); try { await mutations.update.mutateAsync({ id: workout.id, input: inputFor(workout, rpe) }) } catch { setRpeOverrides((current) => ({ ...current, [workout.id]: workout.perceived_exertion })) } finally { setSavingRpe(null) } }
  return <section className="content-card workouts"><div className="section-heading"><div><p className="eyebrow">Movimiento</p><h2>Entrenamientos</h2></div><div className="workout-header-actions">{items[0] && <button className="secondary-button" disabled={mutations.create.isPending} onClick={async () => { const created = await mutations.create.mutateAsync({ ...inputFor(items[0]), started_at: new Date().toISOString() }) as Workout; notify({ message: `${items[0].title} registrado.`, undo: () => mutations.remove.mutateAsync(created.id) }) }} type="button">Repetir último</button>}<button className="secondary-button" onClick={() => setImportOpen(true)} type="button">Importar</button><button className="secondary-button" onClick={() => setOpen(true)} type="button"><Plus size={16} />Registrar</button></div></div>
    {importOpen && <WorkoutImportModal existing={items} onClose={() => setImportOpen(false)} onImport={async (rows) => { for (const row of rows) await mutations.create.mutateAsync(row) }} />}
    {(open || editing) && <div className="home-modal-backdrop" role="presentation"><section aria-modal="true" className="home-modal workout-edit-modal" role="dialog"><WorkoutForm workout={editing} onCancel={() => { setOpen(false); setEditing(undefined) }} onSave={async (input) => { if (editing) { const previous = inputFor(editing); await mutations.update.mutateAsync({ id: editing.id, input }); notify({ message: 'Entrenamiento actualizado.', undo: () => mutations.update.mutateAsync({ id: editing.id, input: previous }) }) } else { const created = await mutations.create.mutateAsync(input) as Workout; notify({ message: 'Entrenamiento registrado.', undo: () => mutations.remove.mutateAsync(created.id) }) } setOpen(false); setEditing(undefined) }} /></section></div>}
    {mutations.create.error || mutations.update.error || mutations.remove.error ? <p className="form-error">No se pudo guardar el entrenamiento.</p> : null}
    <div className="weight-summary"><Stat label="Esta semana" value={`${summary.count} entrenamientos`} /><Stat label="Minutos" value={`${summary.minutes} min`} /><Stat label="Promedio" value={summary.average ? `${summary.average.toFixed(0)} min` : '—'} /><Stat label="RPE" value={summary.rpe ? summary.rpe.toFixed(1) : '—'} /></div>
    <div className="chart-area">{weeks.length ? <ResponsiveContainer height="100%" width="100%"><BarChart data={weeks}><XAxis dataKey="week" /><YAxis /><Tooltip /><Bar dataKey="minutes" fill="#3b82f6" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer> : <div className="chart-empty">Sin minutos registrados</div>}</div>
    {items.length ? <><div className="section-heading workout-list-heading"><h3>{showAll ? 'Todos los entrenamientos' : 'Entrenamientos recientes'}</h3>{items.length > 5 && <button className="text-button" onClick={() => setShowAll((value) => !value)} type="button">{showAll ? 'Ver menos' : `Ver todos (${items.length})`}</button>}</div><div className="weight-entry-list">{visible.map((item) => <article className="weight-entry" key={item.id}><div><strong>{item.title}</strong><time>{new Intl.DateTimeFormat('es-AR', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(item.started_at))}</time><p>{item.activity_type} · {item.duration_minutes} min{item.notes ? ` · ${item.notes}` : ''}</p><label className="workout-rpe-quick">RPE<select aria-label={`RPE de ${item.title}`} disabled={savingRpe === item.id} onChange={(event) => saveRpe(item, event.target.value ? Number(event.target.value) : null)} value={rpeOverrides[item.id] ?? item.perceived_exertion ?? ''}><option value="">Sin RPE</option>{[1,2,3,4,5,6,7,8,9,10].map((rpe) => <option key={rpe} value={rpe}>{rpe}</option>)}</select></label></div><div className="task-actions"><button aria-label="Editar entrenamiento" onClick={() => setEditing(item)} type="button"><Pencil size={16} /></button><button aria-label="Eliminar entrenamiento" onClick={() => { if (window.confirm('¿Eliminar este entrenamiento?')) mutations.remove.mutate(item.id) }} type="button"><Trash2 size={16} /></button></div></article>)}</div></> : <div className="tasks-state"><Dumbbell size={20} />Todavía no hay entrenamientos.</div>}
  </section>
}

function Stat({ label, value }: { label: string; value: string }) { return <article className="weight-stat"><p>{label}</p><strong>{value}</strong></article> }

function WorkoutForm({ workout, onCancel, onSave }: { workout?: Workout; onCancel: () => void; onSave: (input: WorkoutInput) => Promise<void> }) {
  const [form, setForm] = useState(() => formFor(workout)); const [advanced, setAdvanced] = useState(Boolean(workout)); const [error, setError] = useState('')
  const submit = async (event: FormEvent) => { event.preventDefault(); const duration = Number(form.duration); const rpe = form.rpe ? Number(form.rpe) : null; if (!form.title.trim() || duration < 1 || duration > 1440 || (rpe !== null && (rpe < 1 || rpe > 10))) { setError('Completá un título, duración válida y RPE entre 1 y 10.'); return }; await onSave({ title: form.title.trim(), activity_type: form.activity, started_at: new Date(form.started).toISOString(), duration_minutes: duration, perceived_exertion: rpe, notes: form.notes.trim() || null }) }
  return <form className="task-form" onSubmit={submit}><div className="task-form-heading"><h2>{workout ? 'Editar entrenamiento' : 'Registrar entrenamiento'}</h2><button onClick={onCancel} type="button"><X size={18} /></button></div><fieldset className="chip-field"><legend>Actividad</legend><div className="choice-chips">{types.map((type) => <button className={form.activity === type ? 'active' : ''} key={type} onClick={() => setForm({ ...form, activity: type, title: workout ? form.title : typeLabels[type] })} type="button">{typeLabels[type]}</button>)}</div></fieldset><fieldset className="chip-field"><legend>Duración</legend><div className="choice-chips">{[30,45,60].map((minutes) => <button className={form.duration === String(minutes) ? 'active' : ''} key={minutes} onClick={() => setForm({ ...form, duration: String(minutes) })} type="button">{minutes} min</button>)}</div></fieldset><button aria-expanded={advanced} className="text-button disclosure-button" onClick={() => setAdvanced((value) => !value)} type="button">{advanced ? 'Menos opciones' : 'Más opciones'}</button>{advanced && <div className="progressive-fields"><div className="task-form-grid"><label>Título<input onChange={(event) => setForm({ ...form, title: event.target.value })} required value={form.title} /></label><label>Fecha y hora<input onChange={(event) => setForm({ ...form, started: event.target.value })} required type="datetime-local" value={form.started} /></label><label>Duración personalizada<input min="1" onChange={(event) => setForm({ ...form, duration: event.target.value })} required type="number" value={form.duration} /></label><label>RPE (1–10)<input max="10" min="1" onChange={(event) => setForm({ ...form, rpe: event.target.value })} type="number" value={form.rpe} /></label></div><label>Notas<textarea onChange={(event) => setForm({ ...form, notes: event.target.value })} value={form.notes} /></label></div>}{error && <p className="form-error">{error}</p>}<div className="task-form-actions"><button className="secondary-button" onClick={onCancel} type="button">Cancelar</button><button className="primary-button" type="submit">Registrar</button></div></form>
}
