import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { supabase } from '../lib/supabase'
import type { Database } from '../types/database'
export type Workout = Database['public']['Tables']['workouts']['Row']; export type WorkoutInput = Pick<Workout, 'title'|'activity_type'|'started_at'|'duration_minutes'|'perceived_exertion'|'notes'>
export const workoutKey=(id:string)=>['workouts',id] as const
const need=<T,>(r:{data:T|null;error:{message:string}|null})=>{if(r.error)throw new Error(r.error.message);if(r.data===null)throw new Error('Sin respuesta.');return r.data}
export function useWorkouts(id:string|undefined){return useQuery({queryKey:workoutKey(id??''),enabled:Boolean(id),retry:false,queryFn:async()=>need(await supabase.from('workouts').select('*').eq('user_id',id!).order('started_at',{ascending:false}))})}
export function useWorkoutMutations(id:string|undefined){const c=useQueryClient();const done=async()=>{if(id)await c.invalidateQueries({queryKey:workoutKey(id)})};return{create:useMutation({retry:false,mutationFn:async(input:WorkoutInput)=>need(await supabase.from('workouts').insert({...input,user_id:id!,source_id:null,external_id:null}).select().single()),onSuccess:done}),update:useMutation({retry:false,mutationFn:async({id:row,input}:{id:string;input:WorkoutInput})=>need(await supabase.from('workouts').update(input).eq('id',row).eq('user_id',id!).select().single()),onSuccess:done}),remove:useMutation({retry:false,mutationFn:async(row:string)=>need(await supabase.from('workouts').delete().eq('id',row).eq('user_id',id!).select('id').single()),onSuccess:done})}}
export function workoutSummary(items:Workout[]){const since=new Date();since.setDate(since.getDate()-7);const week=items.filter(x=>new Date(x.started_at)>=since);const minutes=week.reduce((s,x)=>s+x.duration_minutes,0);const rpes=week.filter(x=>x.perceived_exertion!==null).map(x=>x.perceived_exertion!);return{count:week.length,minutes,average:week.length?minutes/week.length:null,rpe:rpes.length?rpes.reduce((s,x)=>s+x,0)/rpes.length:null}}
