import { Check, CircleDollarSign, FolderKanban, HeartPulse, ListTodo, Sparkles } from 'lucide-react'
import { useMemo, useState } from 'react'
import { NavLink } from 'react-router-dom'
import { useAuth } from '../auth/AuthProvider'
import { currentFinanceMonth, financeSummary, formatMoney, useFinance } from '../finance/finance'
import { useHealthDashboard } from '../health/dashboardData'
import { getDailySummary, isHabitSuccessful, useHabitMutations, useHabits, type Habit } from '../habits/habits'
import { projectProgress, useProjects } from '../projects/projects'
import { isTaskOverdue, useTasks } from '../tasks/tasks'
import { focusCandidates, focusReason, homeToday, useDailyFocus, useDailyFocusMutation } from './home'

const dateLabel = new Intl.DateTimeFormat('es-AR', { weekday: 'long', day: 'numeric', month: 'long' })
const localDay = (value: string) => new Date(value).toLocaleDateString('en-CA')

export function HomeDashboard() {
  const { user, profile } = useAuth()
  const [pickerOpen, setPickerOpen] = useState(false)
  const today = homeToday()
  const tasks = useTasks(user?.id); const projects = useProjects(user?.id); const focus = useDailyFocus(user?.id, today); const focusMutation = useDailyFocusMutation(user?.id, today)
  const habits = useHabits(user?.id, today); const habitMutation = useHabitMutations(user?.id)
  const health = useHealthDashboard(user?.id, 30); const finance = useFinance(user?.id, currentFinanceMonth())
  const candidates = useMemo(() => focusCandidates(tasks.data ?? [], projects.data ?? []), [tasks.data, projects.data])
  const selected = tasks.data?.find((task) => task.id === focus.data?.task_id) ?? null
  const selectedEligible = selected !== null && candidates.some((task) => task.id === selected.id)
  const overdue = (tasks.data ?? []).filter((task) => isTaskOverdue(task) && (task.linked_entity_type !== 'project' || projects.data?.some((project) => project.id === task.linked_entity_id && project.status === 'active')))
  const greeting = profile?.display_name?.trim() ? `Hola, ${profile.display_name.trim()}` : 'Hola'
  const habitsSummary = habits.data ? getDailySummary(habits.data.habits, habits.data.entries, habits.data.pauses) : null
  const pendingHabits = habitsSummary && habits.data ? habitsSummary.applicable.filter((habit) => !isHabitSuccessful(habit, habits.data!.entries.find((entry) => entry.habit_id === habit.id && entry.entry_date === today))).slice(0, 3) : []

  const pick = (taskId: string, source: 'manual' | 'suggestion') => focusMutation.mutate({ taskId, source }, { onSuccess: () => setPickerOpen(false) })
  return <main className="page home-dashboard">
    <header className="home-header"><div><p className="eyebrow">Torre de control diaria</p><h1>{greeting}</h1><p className="page-description">{dateLabel.format(new Date())}. {candidates.length ? 'Elegí lo importante y avanzá con claridad.' : 'Registrá lo que importa para tener un panorama real.'}</p></div></header>
    <section className="home-focus-layout" aria-label="Foco y atención del día">
      <FocusCard candidates={candidates} error={focus.error ? 'No se pudo cargar el foco guardado.' : null} focus={selected} invalid={Boolean(selected && !selectedEligible)} loading={tasks.isLoading || projects.isLoading || focus.isLoading} onPick={() => setPickerOpen(true)} onSuggested={() => candidates[0] && pick(candidates[0].id, 'suggestion')} />
      {overdue.length > 0 && <article className="home-attention"><span><ListTodo size={18} /></span><div><p className="eyebrow">Atención</p><h2>{overdue.length} tarea{overdue.length === 1 ? '' : 's'} vencida{overdue.length === 1 ? '' : 's'}</h2><p>{overdue.slice(0, 2).map((task) => task.title).join(' · ')}</p></div><NavLink className="text-button" to="/prioridades">Ver matriz</NavLink></article>}
    </section>
    <section className="home-widget-grid" aria-label="Resumen por pilares">
      <HealthWidget query={health} />
      <HabitsWidget habits={habits.data} loading={habits.isLoading} error={habits.error ? 'No se pudieron cargar los hábitos.' : null} pending={pendingHabits} onMark={(habit) => habitMutation.entry.mutate({ habit, date: today, value: habit.tracking_type === 'binary' ? 1 : habit.target_value, status: habit.habit_type === 'break' ? 'avoided' : 'completed' })} saving={habitMutation.entry.isPending} />
      <ProjectsWidget projects={projects.data} tasks={tasks.data} loading={projects.isLoading || tasks.isLoading} error={projects.error || tasks.error ? 'No se pudieron cargar Proyectos y Prioridades.' : null} />
      <FinanceWidget query={finance} />
    </section>
    <ConsistencyHeatmap habits={habits.data} health={health.data} tasks={tasks.data ?? []} finance={finance.data} />
    {pickerOpen && <FocusPicker candidates={candidates} onCancel={() => setPickerOpen(false)} onPick={(task) => pick(task.id, 'manual')} saving={focusMutation.isPending} />}
  </main>
}

function HomeWidget({ children, icon, link, title }: { children: React.ReactNode; icon: React.ReactNode; link: string; title: string }) { return <article className="home-widget"><header><span>{icon}</span><h2>{title}</h2><NavLink aria-label={`Ver ${title}`} to={link}>Ver</NavLink></header>{children}</article> }
function FocusCard({ candidates, error, focus, invalid, loading, onPick, onSuggested }: { candidates: ReturnType<typeof focusCandidates>; error: string | null; focus: ReturnType<typeof focusCandidates>[number] | null; invalid: boolean; loading: boolean; onPick: () => void; onSuggested: () => void }) {
  return <article className="home-focus-card"><div className="home-focus-heading"><span><Sparkles size={20} /></span><div><p className="eyebrow">Foco del día</p><h2>{loading ? 'Cargando foco…' : focus ? focus.title : 'Elegí una tarea importante'}</h2></div></div>{error ? <p className="home-widget-error">{error}</p> : loading ? null : focus ? <><p>{invalid ? 'Esta tarea ya no está activa en Hacer ahora. Elegí un reemplazo explícitamente.' : focusReason(focus)}</p><button className="text-button" onClick={onPick} type="button">Cambiar foco</button></> : candidates.length ? <><p>Sugerencia: <strong>{candidates[0].title}</strong> · {focusReason(candidates[0])}</p><div className="home-focus-actions"><button className="secondary-button" onClick={onSuggested} type="button">Usar sugerencia</button><button className="text-button" onClick={onPick} type="button">Elegir otra</button></div></> : <><p>No hay tareas activas en Hacer ahora.</p><NavLink className="text-button" to="/prioridades">Crear o abrir matriz</NavLink></>}</article>
}
function FocusPicker({ candidates, onCancel, onPick, saving }: { candidates: ReturnType<typeof focusCandidates>; onCancel: () => void; onPick: (task: ReturnType<typeof focusCandidates>[number]) => void; saving: boolean }) { return <div className="home-modal-backdrop" role="presentation"><section aria-modal="true" className="home-modal" role="dialog" aria-labelledby="focus-picker-title"><div className="section-heading"><div><p className="eyebrow">Selección explícita</p><h2 id="focus-picker-title">Elegir foco del día</h2></div><button className="text-button" onClick={onCancel} type="button">Cerrar</button></div>{candidates.length ? <div className="home-picker-list">{candidates.map((task) => <button disabled={saving} key={task.id} onClick={() => onPick(task)} type="button"><strong>{task.title}</strong><span>{focusReason(task)}</span></button>)}</div> : <p>No hay candidatas activas.</p>}</section></div> }
function HealthWidget({ query }: { query: ReturnType<typeof useHealthDashboard> }) { if (query.isLoading) return <HomeWidget icon={<HeartPulse />} link="/salud" title="Salud"><p>Cargando resumen…</p></HomeWidget>; if (query.error || !query.data) return <HomeWidget icon={<HeartPulse />} link="/salud" title="Salud"><p className="home-widget-error">No se pudo cargar Salud.</p></HomeWidget>
  const metric = (slug: string) => query.data!.metrics.find((item) => item.slug === slug); const latest = (slug: string) => { const item = metric(slug); return item ? query.data!.entries.find((entry) => entry.metric_id === item.id) : undefined }; const sleep = latest('sleep_duration'); const steps = latest('steps'); const workout = query.data.workouts[0]
  return <HomeWidget icon={<HeartPulse />} link="/salud" title="Salud"><strong className="home-widget-value">{workout ? workout.title : steps ? `${Number(steps.numeric_value).toLocaleString('es-AR')} pasos` : 'Sin actividad reciente'}</strong><p>{workout ? `Último entrenamiento · ${new Intl.DateTimeFormat('es-AR', { dateStyle: 'short' }).format(new Date(workout.started_at))}` : sleep ? `Sueño registrado: ${sleep.numeric_value} h` : 'Registrá entrenamiento, pasos o recuperación.'}</p><NavLink className="text-button" to="/salud">Ir a Salud</NavLink></HomeWidget>
}
function HabitsWidget({ habits, loading, error, pending, onMark, saving }: { habits: ReturnType<typeof useHabits>['data']; loading: boolean; error: string | null; pending: Habit[]; onMark: (habit: Habit) => void; saving: boolean }) { if (loading) return <HomeWidget icon={<Check />} link="/habitos" title="Hábitos"><p>Cargando resumen…</p></HomeWidget>; if (error || !habits) return <HomeWidget icon={<Check />} link="/habitos" title="Hábitos"><p className="home-widget-error">{error}</p></HomeWidget>; const summary = getDailySummary(habits.habits, habits.entries, habits.pauses); return <HomeWidget icon={<Check />} link="/habitos" title="Hábitos"><strong className="home-widget-value">{summary.completed}/{summary.applicable.length} · {summary.score.toFixed(0)}%</strong>{pending.length ? <ul className="home-quick-list">{pending.map((habit) => <li key={habit.id}><span>{habit.name}</span><button disabled={saving} onClick={() => onMark(habit)} type="button">Marcar</button></li>)}</ul> : <p>{summary.applicable.length ? 'Todos los hábitos aplicables están al día.' : 'No hay hábitos aplicables hoy.'}</p>}<NavLink className="text-button" to="/habitos">Ver hábitos</NavLink></HomeWidget> }
function ProjectsWidget({ projects, tasks, loading, error }: { projects: ReturnType<typeof useProjects>['data']; tasks: ReturnType<typeof useTasks>['data']; loading: boolean; error: string | null }) { if (loading) return <HomeWidget icon={<FolderKanban />} link="/proyectos" title="Proyectos y prioridades"><p>Cargando resumen…</p></HomeWidget>; if (error || !projects || !tasks) return <HomeWidget icon={<FolderKanban />} link="/proyectos" title="Proyectos y prioridades"><p className="home-widget-error">{error}</p></HomeWidget>; const projectTasks = tasks ?? []; const active = projects.filter((project) => project.status === 'active'); const next = focusCandidates(projectTasks, projects)[0]; const highlighted = active[0]; const progress = highlighted ? projectProgress(highlighted, projectTasks) : null; return <HomeWidget icon={<FolderKanban />} link="/proyectos" title="Proyectos y prioridades"><strong className="home-widget-value">{next ? next.title : `${active.length} proyectos activos`}</strong><p>{next ? `Hacer ahora · ${focusReason(next)}` : highlighted ? `${highlighted.name}${progress?.percent === null ? ' · sin tareas' : ` · ${progress?.percent.toFixed(0)}%`}` : 'No hay proyectos activos ni prioridades urgentes.'}</p><div className="home-link-row"><NavLink className="text-button" to="/proyectos">Proyectos</NavLink><NavLink className="text-button" to="/prioridades">Matriz</NavLink></div></HomeWidget> }
function FinanceWidget({ query }: { query: ReturnType<typeof useFinance> }) { if (query.isLoading) return <HomeWidget icon={<CircleDollarSign />} link="/finanzas" title="Finanzas"><p>Cargando resumen…</p></HomeWidget>; if (query.error || !query.data) return <HomeWidget icon={<CircleDollarSign />} link="/finanzas" title="Finanzas"><p className="home-widget-error">No se pudieron cargar las finanzas.</p></HomeWidget>; const summary = financeSummary(query.data, currentFinanceMonth()); const hidden = query.data.preferences?.hide_amounts ?? false; const latest = query.data.transactions[0]; return <HomeWidget icon={<CircleDollarSign />} link="/finanzas" title="Finanzas"><strong className="home-widget-value">{hidden ? 'Importes ocultos' : summary.dailyAvailable !== null ? `Disponible hoy: ${formatMoney(summary.dailyAvailable)}` : `Balance: ${formatMoney(summary.total)}`}</strong><p>{latest ? `Último movimiento · ${new Intl.DateTimeFormat('es-AR', { dateStyle: 'short' }).format(new Date(latest.occurred_at))}` : hidden ? 'Configurá importes desde Finanzas.' : `Mes: ${formatMoney(summary.income)} ingresos · ${formatMoney(summary.expense)} gastos`}</p><NavLink className="text-button" to="/finanzas">Ir a Finanzas</NavLink></HomeWidget> }
function ConsistencyHeatmap({ habits, health, tasks, finance }: { habits: ReturnType<typeof useHabits>['data']; health: ReturnType<typeof useHealthDashboard>['data']; tasks: NonNullable<ReturnType<typeof useTasks>['data']>; finance: ReturnType<typeof useFinance>['data'] }) { const days = Array.from({ length: 84 }, (_, i) => { const date = new Date(); date.setDate(date.getDate() - (83 - i)); const day = date.toLocaleDateString('en-CA'); const habit = habits ? getDailySummary(habits.habits, habits.entries, habits.pauses, date) : null; const healthActive = health ? health.workouts.some((item) => localDay(item.started_at) === day) || health.entries.some((item) => (item.check_in_date ?? localDay(item.recorded_at)) === day) : false; const taskActive = tasks.some((task) => task.completed_at && localDay(task.completed_at) === day); const financeActive = finance?.transactions.some((item) => item.status === 'confirmed' && localDay(item.occurred_at) === day) ?? false; return { day, habit: habit?.applicable.length ? habit.score : null, health: healthActive, tasks: taskActive, finance: financeActive } }); return <section className="home-heatmap"><div className="section-heading"><div><p className="eyebrow">Registro, no puntuación</p><h2>Constancia general</h2></div><span className="section-status">Últimas 12 semanas</span></div><p>Cuatro segmentos por día: Salud, Hábitos, Prioridades y Finanzas. La intensidad sólo representa el cumplimiento de hábitos.</p><div className="home-heatmap-grid">{days.map((item) => <div aria-label={`${item.day}. Salud: ${item.health ? 'registrada' : 'sin registro'}; Hábitos: ${item.habit === null ? 'sin oportunidades' : `${item.habit.toFixed(0)}%`}; Prioridades: ${item.tasks ? 'registradas' : 'sin registro'}; Finanzas: ${item.finance ? 'registradas' : 'sin registro'}`} className="home-heatmap-day" key={item.day} title={item.day}><i className={item.health ? 'active' : ''} /><i className={item.habit === null ? '' : item.habit >= 80 ? 'habit-high' : item.habit > 0 ? 'habit-low' : 'habit-none'} /><i className={item.tasks ? 'active' : ''} /><i className={item.finance ? 'active' : ''} /></div>)}</div><div className="home-heatmap-legend"><span><i />Salud</span><span><i />Hábitos</span><span><i />Prioridades</span><span><i />Finanzas</span></div></section> }
