export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: { Row: { id: string; created_at: string; updated_at: string }; Insert: { id: string; created_at?: string; updated_at?: string }; Update: { id?: string; created_at?: string; updated_at?: string }; Relationships: [] }
      data_sources: { Row: { id: string; user_id: string; name: string; source_type: string; provider: string | null; external_account_id: string | null; metadata: Json; created_at: string; updated_at: string }; Insert: { id?: string; user_id: string; name: string; source_type: string; provider?: string | null; external_account_id?: string | null; metadata?: Json; created_at?: string; updated_at?: string }; Update: { id?: string; user_id?: string; name?: string; source_type?: string; provider?: string | null; external_account_id?: string | null; metadata?: Json; created_at?: string; updated_at?: string }; Relationships: [] }
      metrics: { Row: { id: string; user_id: string; name: string; slug: string | null; pillar: string; data_type: string; unit: string | null; aggregation: string; created_at: string; updated_at: string }; Insert: { id?: string; user_id: string; name: string; slug?: string | null; pillar: string; data_type: string; unit?: string | null; aggregation: string; created_at?: string; updated_at?: string }; Update: { id?: string; user_id?: string; name?: string; slug?: string | null; pillar?: string; data_type?: string; unit?: string | null; aggregation?: string; created_at?: string; updated_at?: string }; Relationships: [] }
      metric_entries: { Row: { id: string; user_id: string; metric_id: string; data_source_id: string; numeric_value: number | null; text_value: string | null; boolean_value: boolean | null; recorded_at: string; check_in_date: string | null; external_id: string | null; metadata: Json; created_at: string; updated_at: string }; Insert: { id?: string; user_id: string; metric_id: string; data_source_id: string; numeric_value?: number | null; text_value?: string | null; boolean_value?: boolean | null; recorded_at?: string; check_in_date?: string | null; external_id?: string | null; metadata?: Json; created_at?: string; updated_at?: string }; Update: { id?: string; user_id?: string; metric_id?: string; data_source_id?: string; numeric_value?: number | null; text_value?: string | null; boolean_value?: boolean | null; recorded_at?: string; check_in_date?: string | null; external_id?: string | null; metadata?: Json; created_at?: string; updated_at?: string }; Relationships: [] }
      workouts: { Row: { id: string; user_id: string; title: string; activity_type: string; started_at: string; duration_minutes: number; perceived_exertion: number | null; notes: string | null; source_id: string | null; external_id: string | null; created_at: string; updated_at: string }; Insert: { id?: string; user_id: string; title: string; activity_type: string; started_at: string; duration_minutes: number; perceived_exertion?: number | null; notes?: string | null; source_id?: string | null; external_id?: string | null; created_at?: string; updated_at?: string }; Update: { id?: string; user_id?: string; title?: string; activity_type?: string; started_at?: string; duration_minutes?: number; perceived_exertion?: number | null; notes?: string | null; source_id?: string | null; external_id?: string | null; created_at?: string; updated_at?: string }; Relationships: [] }
      health_settings: { Row: { user_id: string; timezone: string; water_goal_ml: number; steps_goal: number; show_readiness: boolean; created_at: string; updated_at: string }; Insert: { user_id: string; timezone?: string; water_goal_ml?: number; steps_goal?: number; show_readiness?: boolean; created_at?: string; updated_at?: string }; Update: { user_id?: string; timezone?: string; water_goal_ml?: number; steps_goal?: number; show_readiness?: boolean; created_at?: string; updated_at?: string }; Relationships: [] }
      exercises: { Row: { id: string; user_id: string; name: string; load_type: string; primary_muscle: string | null; secondary_muscles: string[]; created_at: string; updated_at: string }; Insert: { id?: string; user_id: string; name: string; load_type: string; primary_muscle?: string | null; secondary_muscles?: string[]; created_at?: string; updated_at?: string }; Update: { id?: string; user_id?: string; name?: string; load_type?: string; primary_muscle?: string | null; secondary_muscles?: string[]; created_at?: string; updated_at?: string }; Relationships: [] }
      workout_exercises: { Row: { id: string; user_id: string; workout_id: string; exercise_id: string; position: number; created_at: string; updated_at: string }; Insert: { id?: string; user_id: string; workout_id: string; exercise_id: string; position: number; created_at?: string; updated_at?: string }; Update: { id?: string; user_id?: string; workout_id?: string; exercise_id?: string; position?: number; created_at?: string; updated_at?: string }; Relationships: [] }
      workout_sets: { Row: { id: string; user_id: string; workout_exercise_id: string; position: number; repetitions: number | null; weight_kg: number | null; distance_meters: number | null; duration_seconds: number | null; perceived_exertion: number | null; is_warmup: boolean; created_at: string; updated_at: string }; Insert: { id?: string; user_id: string; workout_exercise_id: string; position: number; repetitions?: number | null; weight_kg?: number | null; distance_meters?: number | null; duration_seconds?: number | null; perceived_exertion?: number | null; is_warmup?: boolean; created_at?: string; updated_at?: string }; Update: { id?: string; user_id?: string; workout_exercise_id?: string; position?: number; repetitions?: number | null; weight_kg?: number | null; distance_meters?: number | null; duration_seconds?: number | null; perceived_exertion?: number | null; is_warmup?: boolean; created_at?: string; updated_at?: string }; Relationships: [] }
      goals: { Row: { id: string; user_id: string; pillar: string; title: string; description: string | null; metric_id: string | null; target_type: string; target_value: number | null; start_value: number | null; start_date: string; due_date: string | null; status: string; created_at: string; updated_at: string }; Insert: { id?: string; user_id: string; pillar: string; title: string; description?: string | null; metric_id?: string | null; target_type: string; target_value?: number | null; start_value?: number | null; start_date?: string; due_date?: string | null; status?: string; created_at?: string; updated_at?: string }; Update: { id?: string; user_id?: string; pillar?: string; title?: string; description?: string | null; metric_id?: string | null; target_type?: string; target_value?: number | null; start_value?: number | null; start_date?: string; due_date?: string | null; status?: string; created_at?: string; updated_at?: string }; Relationships: [] }
      habits: { Row: { id: string; user_id: string; name: string; description: string | null; pillar: string; frequency_type: string; target_count: number; days_of_week: number[] | null; start_date: string; end_date: string | null; is_active: boolean; habit_type: string; tracking_type: string; time_of_day: string; target_value: number; unit: string | null; minimum_success_value: number; linked_entity_type: string | null; linked_entity_id: string | null; created_at: string; updated_at: string }; Insert: { id?: string; user_id: string; name: string; description?: string | null; pillar?: string; frequency_type: string; target_count?: number; days_of_week?: number[] | null; start_date?: string; end_date?: string | null; is_active?: boolean; habit_type?: string; tracking_type?: string; time_of_day?: string; target_value?: number; unit?: string | null; minimum_success_value?: number; linked_entity_type?: string | null; linked_entity_id?: string | null; created_at?: string; updated_at?: string }; Update: { id?: string; user_id?: string; name?: string; description?: string | null; pillar?: string; frequency_type?: string; target_count?: number; days_of_week?: number[] | null; start_date?: string; end_date?: string | null; is_active?: boolean; habit_type?: string; tracking_type?: string; time_of_day?: string; target_value?: number; unit?: string | null; minimum_success_value?: number; linked_entity_type?: string | null; linked_entity_id?: string | null; created_at?: string; updated_at?: string }; Relationships: [] }
      habit_entries: { Row: { id: string; user_id: string; habit_id: string; entry_date: string; completed_count: number; value: number | null; status: string | null; skipped_reason: string | null; notes: string | null; created_at: string; updated_at: string }; Insert: { id?: string; user_id: string; habit_id: string; entry_date: string; completed_count?: number; value?: number | null; status?: string | null; skipped_reason?: string | null; notes?: string | null; created_at?: string; updated_at?: string }; Update: { id?: string; user_id?: string; habit_id?: string; entry_date?: string; completed_count?: number; value?: number | null; status?: string |null; skipped_reason?: string | null; notes?: string | null; created_at?: string; updated_at?: string }; Relationships: [] }
      habit_pause_periods: { Row: { id:string; user_id:string; habit_id:string; starts_on:string; ends_on:string|null; created_at:string; updated_at:string }; Insert: { id?:string; user_id:string; habit_id:string; starts_on?:string; ends_on?:string|null; created_at?:string; updated_at?:string }; Update: { id?:string; user_id?:string; habit_id?:string; starts_on?:string; ends_on?:string|null; created_at?:string; updated_at?:string }; Relationships: [] }
      habit_preferences: { Row: { user_id:string; general_streak_threshold:number; created_at:string; updated_at:string }; Insert: { user_id:string; general_streak_threshold?:number; created_at?:string; updated_at?:string }; Update: { user_id?:string; general_streak_threshold?:number; created_at?:string; updated_at?:string }; Relationships: [] }
      habit_routines: { Row: { id:string; user_id:string; name:string; description:string|null; time_of_day:string|null; is_active:boolean; created_at:string; updated_at:string }; Insert: { id?:string; user_id:string; name:string; description?:string|null; time_of_day?:string|null; is_active?:boolean; created_at?:string; updated_at?:string }; Update: { id?:string; user_id?:string; name?:string; description?:string|null; time_of_day?:string|null; is_active?:boolean; created_at?:string; updated_at?:string }; Relationships: [] }
      habit_routine_items: { Row: { id:string; user_id:string; routine_id:string; habit_id:string; position:number; trigger_text:string|null; created_at:string; updated_at:string }; Insert: { id?:string; user_id:string; routine_id:string; habit_id:string; position:number; trigger_text?:string|null; created_at?:string; updated_at?:string }; Update: { id?:string; user_id?:string; routine_id?:string; habit_id?:string; position?:number; trigger_text?:string|null; created_at?:string; updated_at?:string }; Relationships: [] }
      projects: { Row: { id: string; user_id: string; name: string; description: string | null; status: string; priority: string; start_date: string | null; due_date: string | null; progress_mode: string; completed_at: string | null; created_at: string; updated_at: string }; Insert: { id?: string; user_id: string; name: string; description?: string | null; status?: string; priority?: string; start_date?: string | null; due_date?: string | null; progress_mode?: string; completed_at?: string | null; created_at?: string; updated_at?: string }; Update: { id?: string; user_id?: string; name?: string; description?: string | null; status?: string; priority?: string; start_date?: string | null; due_date?: string | null; progress_mode?: string; completed_at?: string | null; created_at?: string; updated_at?: string }; Relationships: [] }
      finance_accounts: { Row: { id:string; user_id:string; name:string; account_type:string; currency:string; is_active:boolean; opening_balance_minor:number; opening_balance_at:string; balance_role:string; created_at:string; updated_at:string }; Insert: { id?:string; user_id:string; name:string; account_type:string; currency?:string; is_active?:boolean; opening_balance_minor?:number; opening_balance_at?:string; balance_role?:string; created_at?:string; updated_at?:string }; Update: { id?:string; user_id?:string; name?:string; account_type?:string; currency?:string; is_active?:boolean; opening_balance_minor?:number; opening_balance_at?:string; balance_role?:string; created_at?:string; updated_at?:string }; Relationships: [] }
      finance_categories: { Row: { id:string; user_id:string; name:string; category_type:string; is_active:boolean; created_at:string; updated_at:string }; Insert: { id?:string; user_id:string; name:string; category_type:string; is_active?:boolean; created_at?:string; updated_at?:string }; Update: { id?:string; user_id?:string; name?:string; category_type?:string; is_active?:boolean; created_at?:string; updated_at?:string }; Relationships: [] }
      finance_transactions: { Row: { id:string; user_id:string; account_id:string; category_id:string|null; transaction_type:string; amount_minor:number; status:string; occurred_at:string; notes:string|null; created_at:string; updated_at:string }; Insert: { id?:string; user_id:string; account_id:string; category_id?:string|null; transaction_type:string; amount_minor:number; status?:string; occurred_at?:string; notes?:string|null; created_at?:string; updated_at?:string }; Update: { id?:string; user_id?:string; account_id?:string; category_id?:string|null; transaction_type?:string; amount_minor?:number; status?:string; occurred_at?:string; notes?:string|null; created_at?:string; updated_at?:string }; Relationships: [] }
      finance_budget_periods: { Row: { id:string; user_id:string; month_start:string; status:string; created_at:string; updated_at:string }; Insert: { id?:string; user_id:string; month_start:string; status?:string; created_at?:string; updated_at?:string }; Update: { id?:string; user_id?:string; month_start?:string; status?:string; created_at?:string; updated_at?:string }; Relationships: [] }
      finance_budget_allocations: { Row: { id:string; user_id:string; budget_period_id:string; category_id:string; limit_minor:number; created_at:string; updated_at:string }; Insert: { id?:string; user_id:string; budget_period_id:string; category_id:string; limit_minor:number; created_at?:string; updated_at?:string }; Update: { id?:string; user_id?:string; budget_period_id?:string; category_id?:string; limit_minor?:number; created_at?:string; updated_at?:string }; Relationships: [] }
      finance_preferences: { Row: { user_id:string; hide_amounts:boolean; created_at:string; updated_at:string }; Insert: { user_id:string; hide_amounts?:boolean; created_at?:string; updated_at?:string }; Update: { user_id?:string; hide_amounts?:boolean; created_at?:string; updated_at?:string }; Relationships: [] }
      tasks: { Row: { id: string; user_id: string; title: string; description: string | null; pillar: string | null; linked_entity_type: string | null; linked_entity_id: string | null; is_urgent: boolean; is_important: boolean; status: string; due_at: string | null; scheduled_at: string | null; estimated_duration_minutes: number | null; completed_at: string | null; manual_order: number; start_at: string | null; energy_required: string | null; focus_mode: string | null; created_at: string; updated_at: string }; Insert: { id?: string; user_id: string; title: string; description?: string | null; pillar?: string | null; linked_entity_type?: string | null; linked_entity_id?: string | null; is_urgent?: boolean; is_important?: boolean; status?: string; due_at?: string | null; scheduled_at?: string | null; estimated_duration_minutes?: number | null; completed_at?: string | null; manual_order?: number; start_at?: string | null; energy_required?: string | null; focus_mode?: string | null; created_at?: string; updated_at?: string }; Update: { id?: string; user_id?: string; title?: string; description?: string | null; pillar?: string | null; linked_entity_type?: string | null; linked_entity_id?: string | null; is_urgent?: boolean; is_important?: boolean; status?: string; due_at?: string | null; scheduled_at?: string | null; estimated_duration_minutes?: number | null; completed_at?: string | null; manual_order?: number; start_at?: string | null; energy_required?: string | null; focus_mode?: string | null; created_at?: string; updated_at?: string }; Relationships: [] }
    }
    Views: { [_ in never]: never }
    Functions: { [_ in never]: never }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
}
