export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: { Row: { id: string; created_at: string; updated_at: string }; Insert: { id: string; created_at?: string; updated_at?: string }; Update: { id?: string; created_at?: string; updated_at?: string }; Relationships: [] }
      data_sources: { Row: { id: string; user_id: string; name: string; source_type: string; provider: string | null; external_account_id: string | null; metadata: Json; created_at: string; updated_at: string }; Insert: { id?: string; user_id: string; name: string; source_type: string; provider?: string | null; external_account_id?: string | null; metadata?: Json; created_at?: string; updated_at?: string }; Update: { id?: string; user_id?: string; name?: string; source_type?: string; provider?: string | null; external_account_id?: string | null; metadata?: Json; created_at?: string; updated_at?: string }; Relationships: [] }
      metrics: { Row: { id: string; user_id: string; name: string; slug: string | null; pillar: string; data_type: string; unit: string | null; aggregation: string; created_at: string; updated_at: string }; Insert: { id?: string; user_id: string; name: string; slug?: string | null; pillar: string; data_type: string; unit?: string | null; aggregation: string; created_at?: string; updated_at?: string }; Update: { id?: string; user_id?: string; name?: string; slug?: string | null; pillar?: string; data_type?: string; unit?: string | null; aggregation?: string; created_at?: string; updated_at?: string }; Relationships: [] }
      metric_entries: { Row: { id: string; user_id: string; metric_id: string; data_source_id: string; numeric_value: number | null; text_value: string | null; boolean_value: boolean | null; recorded_at: string; check_in_date: string | null; external_id: string | null; metadata: Json; created_at: string; updated_at: string }; Insert: { id?: string; user_id: string; metric_id: string; data_source_id: string; numeric_value?: number | null; text_value?: string | null; boolean_value?: boolean | null; recorded_at?: string; check_in_date?: string | null; external_id?: string | null; metadata?: Json; created_at?: string; updated_at?: string }; Update: { id?: string; user_id?: string; metric_id?: string; data_source_id?: string; numeric_value?: number | null; text_value?: string | null; boolean_value?: boolean | null; recorded_at?: string; check_in_date?: string | null; external_id?: string | null; metadata?: Json; created_at?: string; updated_at?: string }; Relationships: [] }
      workouts: { Row: { id: string; user_id: string; title: string; activity_type: string; started_at: string; duration_minutes: number; perceived_exertion: number | null; notes: string | null; source_id: string | null; external_id: string | null; created_at: string; updated_at: string }; Insert: { id?: string; user_id: string; title: string; activity_type: string; started_at: string; duration_minutes: number; perceived_exertion?: number | null; notes?: string | null; source_id?: string | null; external_id?: string | null; created_at?: string; updated_at?: string }; Update: { id?: string; user_id?: string; title?: string; activity_type?: string; started_at?: string; duration_minutes?: number; perceived_exertion?: number | null; notes?: string | null; source_id?: string | null; external_id?: string | null; created_at?: string; updated_at?: string }; Relationships: [] }
      goals: { Row: { id: string; user_id: string; pillar: string; title: string; description: string | null; metric_id: string | null; target_type: string; target_value: number | null; start_value: number | null; start_date: string; due_date: string | null; status: string; created_at: string; updated_at: string }; Insert: { id?: string; user_id: string; pillar: string; title: string; description?: string | null; metric_id?: string | null; target_type: string; target_value?: number | null; start_value?: number | null; start_date?: string; due_date?: string | null; status?: string; created_at?: string; updated_at?: string }; Update: { id?: string; user_id?: string; pillar?: string; title?: string; description?: string | null; metric_id?: string | null; target_type?: string; target_value?: number | null; start_value?: number | null; start_date?: string; due_date?: string | null; status?: string; created_at?: string; updated_at?: string }; Relationships: [] }
      habits: { Row: { id: string; user_id: string; name: string; description: string | null; pillar: string; frequency_type: string; target_count: number; days_of_week: number[] | null; start_date: string; end_date: string | null; is_active: boolean; linked_entity_type: string | null; linked_entity_id: string | null; created_at: string; updated_at: string }; Insert: { id?: string; user_id: string; name: string; description?: string | null; pillar?: string; frequency_type: string; target_count?: number; days_of_week?: number[] | null; start_date?: string; end_date?: string | null; is_active?: boolean; linked_entity_type?: string | null; linked_entity_id?: string | null; created_at?: string; updated_at?: string }; Update: { id?: string; user_id?: string; name?: string; description?: string | null; pillar?: string; frequency_type?: string; target_count?: number; days_of_week?: number[] | null; start_date?: string; end_date?: string | null; is_active?: boolean; linked_entity_type?: string | null; linked_entity_id?: string | null; created_at?: string; updated_at?: string }; Relationships: [] }
      habit_entries: { Row: { id: string; user_id: string; habit_id: string; entry_date: string; completed_count: number; notes: string | null; created_at: string; updated_at: string }; Insert: { id?: string; user_id: string; habit_id: string; entry_date: string; completed_count?: number; notes?: string | null; created_at?: string; updated_at?: string }; Update: { id?: string; user_id?: string; habit_id?: string; entry_date?: string; completed_count?: number; notes?: string | null; created_at?: string; updated_at?: string }; Relationships: [] }
      projects: { Row: { id: string; user_id: string; name: string; description: string | null; status: string; priority: string; start_date: string | null; due_date: string | null; progress_mode: string; created_at: string; updated_at: string }; Insert: { id?: string; user_id: string; name: string; description?: string | null; status?: string; priority?: string; start_date?: string | null; due_date?: string | null; progress_mode?: string; created_at?: string; updated_at?: string }; Update: { id?: string; user_id?: string; name?: string; description?: string | null; status?: string; priority?: string; start_date?: string | null; due_date?: string | null; progress_mode?: string; created_at?: string; updated_at?: string }; Relationships: [] }
      finance_accounts: { Row: { id:string; user_id:string; name:string; account_type:string; currency:string; is_active:boolean; created_at:string; updated_at:string }; Insert: { id?:string; user_id:string; name:string; account_type:string; currency?:string; is_active?:boolean; created_at?:string; updated_at?:string }; Update: { id?:string; user_id?:string; name?:string; account_type?:string; currency?:string; is_active?:boolean; created_at?:string; updated_at?:string }; Relationships: [] }
      finance_categories: { Row: { id:string; user_id:string; name:string; category_type:string; is_active:boolean; created_at:string; updated_at:string }; Insert: { id?:string; user_id:string; name:string; category_type:string; is_active?:boolean; created_at?:string; updated_at?:string }; Update: { id?:string; user_id?:string; name?:string; category_type?:string; is_active?:boolean; created_at?:string; updated_at?:string }; Relationships: [] }
      finance_transactions: { Row: { id:string; user_id:string; account_id:string; category_id:string|null; transaction_type:string; amount:number; status:string; occurred_at:string; notes:string|null; created_at:string; updated_at:string }; Insert: { id?:string; user_id:string; account_id:string; category_id?:string|null; transaction_type:string; amount:number; status?:string; occurred_at?:string; notes?:string|null; created_at?:string; updated_at?:string }; Update: { id?:string; user_id?:string; account_id?:string; category_id?:string|null; transaction_type?:string; amount?:number; status?:string; occurred_at?:string; notes?:string|null; created_at?:string; updated_at?:string }; Relationships: [] }
      tasks: { Row: { id: string; user_id: string; title: string; description: string | null; pillar: string | null; linked_entity_type: string | null; linked_entity_id: string | null; is_urgent: boolean; is_important: boolean; status: string; due_at: string | null; scheduled_at: string | null; estimated_duration_minutes: number | null; completed_at: string | null; created_at: string; updated_at: string }; Insert: { id?: string; user_id: string; title: string; description?: string | null; pillar?: string | null; linked_entity_type?: string | null; linked_entity_id?: string | null; is_urgent?: boolean; is_important?: boolean; status?: string; due_at?: string | null; scheduled_at?: string | null; estimated_duration_minutes?: number | null; completed_at?: string | null; created_at?: string; updated_at?: string }; Update: { id?: string; user_id?: string; title?: string; description?: string | null; pillar?: string | null; linked_entity_type?: string | null; linked_entity_id?: string | null; is_urgent?: boolean; is_important?: boolean; status?: string; due_at?: string | null; scheduled_at?: string | null; estimated_duration_minutes?: number | null; completed_at?: string | null; created_at?: string; updated_at?: string }; Relationships: [] }
    }
    Views: { [_ in never]: never }
    Functions: { [_ in never]: never }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
}
