import { DndContext, DragOverlay, KeyboardSensor, MouseSensor, useDraggable, useDroppable, useSensor, useSensors, type DragEndEvent, type DragStartEvent } from '@dnd-kit/core'
import { Check, ChevronDown, Clock3, GripVertical, Pencil, Plus, Trash2, X } from 'lucide-react'
import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react'
import { useAuth } from '../auth/AuthProvider'
import { useLocation } from 'react-router-dom'
import { useProjects } from '../projects/projects'
import { filterPriorityTasks, findTaskQuadrant, isTaskOverdue, isTaskInQuadrant, taskQuadrants, type Task, type TaskInput, type TaskPillarFilter, type TaskQuadrant, type TaskStateFilter, useTaskMutations, useTasks } from './tasks'

type FormState = { title: string; description: string; pillar: string; urgent: boolean; important: boolean; dueAt: string; scheduledAt: string; duration: string; startAt: string; energy: string; focus: string }
const toLocalInput = (value: string | null) => value ? value.slice(0, 16) : ''
const initialForm = (task?: Task, quadrant?: TaskQuadrant): FormState => ({ title: task?.title ?? '', description: task?.description ?? '', pillar: task?.pillar ?? '', urgent: task?.is_urgent ?? quadrant?.isUrgent ?? false, important: task?.is_important ?? quadrant?.isImportant ?? false, dueAt: toLocalInput(task?.due_at ?? null), scheduledAt: toLocalInput(task?.scheduled_at ?? null), duration: task?.estimated_duration_minutes?.toString() ?? '', startAt: toLocalInput(task?.start_at ?? null), energy: task?.energy_required ?? '', focus: task?.focus_mode ?? '' })
const pillars: { value: TaskPillarFilter; label: string }[] = [{ value: 'all', label: 'Todos' }, { value: 'health', label: 'Salud' }, { value: 'finance', label: 'Finanzas' }, { value: 'projects', label: 'Proyectos' }, { value: 'habits', label: 'Hábitos' }, { value: 'manual', label: 'Manuales u otros' }]

function useDesktop() { const [desktop, setDesktop] = useState(() => window.matchMedia('(min-width: 720px)').matches); useEffect(() => { const media = window.matchMedia('(min-width: 720px)'); const listener = () => setDesktop(media.matches); listener(); media.addEventListener('change', listener); return () => media.removeEventListener('change', listener) }, []); return desktop }

export function TasksBoard() {
  const { user } = useAuth(); const tasksQuery = useTasks(user?.id); const projectsQuery = useProjects(user?.id); const mutations = useTaskMutations(user?.id); const desktop = useDesktop()
  const location = useLocation()
  const [editingTask, setEditingTask] = useState<Task | null>(null); const [creatingQuadrant, setCreatingQuadrant] = useState<TaskQuadrant | null>(() => (location.state as { openAction?: string } | null)?.openAction === 'task' ? taskQuadrants[0] : null); const [pillar, setPillar] = useState<TaskPillarFilter>('all'); const [state, setState] = useState<TaskStateFilter>('active'); const [includePausedProjects, setIncludePausedProjects] = useState(false); const [activeTone, setActiveTone] = useState<TaskQuadrant['tone']>('now'); const [draggedTask, setDraggedTask] = useState<Task | null>(null); const [announcement, setAnnouncement] = useState('')
  const tasks = tasksQuery.data ?? []
  const visibleTasks = useMemo(() => filterPriorityTasks(tasksQuery.data ?? [], projectsQuery.data ?? [], { pillar, state, includePausedProjects }), [tasksQuery.data, projectsQuery.data, pillar, state, includePausedProjects])
  const sensors = useSensors(useSensor(MouseSensor, { activationConstraint: { distance: 6 } }), useSensor(KeyboardSensor))
  const moveTo = (task: Task, quadrant: TaskQuadrant) => { if (isTaskInQuadrant(task, quadrant) || mutations.setTaskQuadrant.isPending) return; setAnnouncement(`${task.title} movida a ${quadrant.title}. Guardando cambio.`); mutations.setTaskQuadrant.mutate({ id: task.id, isUrgent: quadrant.isUrgent, isImportant: quadrant.isImportant }, { onError: () => setAnnouncement(`No se pudo mover ${task.title}. Se restauró su cuadrante anterior.`), onSuccess: () => setAnnouncement(`${task.title} está en ${quadrant.title}.`) }) }
  const onDragEnd = ({ active, over }: DragEndEvent) => { setDraggedTask(null); const target = taskQuadrants.find((quadrant) => quadrant.tone === over?.id); const task = tasks.find((item) => item.id === active.id); if (target && task) moveTo(task, target) }
  if (tasksQuery.isLoading || projectsQuery.isLoading) return <div className="tasks-state">Cargando tareas…</div>
  if (tasksQuery.error || projectsQuery.error) return <div className="tasks-state tasks-state--error">No se pudieron cargar las prioridades. Intentá de nuevo.</div>
  return <><PriorityFilters includePausedProjects={includePausedProjects} pillar={pillar} setIncludePausedProjects={setIncludePausedProjects} setPillar={setPillar} setState={setState} state={state} />
    <div className="priorities-action"><button className="primary-button" onClick={() => setCreatingQuadrant(taskQuadrants[0])} type="button"><Plus size={18} />Nueva tarea</button></div>
    {(creatingQuadrant || editingTask) && <TaskEditor quadrant={creatingQuadrant ?? undefined} task={editingTask ?? undefined} onCancel={() => { setCreatingQuadrant(null); setEditingTask(null) }} onSubmit={async (input) => { if (editingTask) await mutations.updateTask.mutateAsync({ id: editingTask.id, input }); else await mutations.createTask.mutateAsync(input); setCreatingQuadrant(null); setEditingTask(null) }} />}
    {mutations.createTask.error || mutations.updateTask.error || mutations.completeTask.error || mutations.deleteTask.error ? <div className="tasks-state tasks-state--error">No se pudo guardar el cambio. Intentá de nuevo.</div> : null}
    <p aria-live="polite" className="sr-only">{announcement}</p>
    <DndContext onDragEnd={onDragEnd} onDragStart={({ active }: DragStartEvent) => { const task = tasks.find((item) => item.id === active.id) ?? null; setDraggedTask(task); if (task) setAnnouncement(`Moviendo ${task.title}. Elegí un cuadrante.`) }} sensors={desktop ? sensors : []}>
      <PriorityAxes />
      <div className="priority-grid" role={desktop ? undefined : 'tablist'} aria-label="Cuadrantes de prioridades">{taskQuadrants.map((quadrant) => { const quadrantTasks = visibleTasks.filter((task) => isTaskInQuadrant(task, quadrant)); const selected = activeTone === quadrant.tone; return <PriorityQuadrant active={selected} desktop={desktop} key={quadrant.tone} onCreate={() => setCreatingQuadrant(quadrant)} onSelect={() => setActiveTone(quadrant.tone)} quadrant={quadrant} tasks={quadrantTasks}>{quadrantTasks.map((task) => <PriorityTaskCard draggable={desktop} key={task.id} task={task} onComplete={() => mutations.completeTask.mutate({ id: task.id, completed: task.status !== 'completed' })} onDelete={() => { if (window.confirm(`¿Eliminar “${task.title}”?`)) mutations.deleteTask.mutate(task.id) }} onEdit={() => setEditingTask(task)} onMove={(target) => moveTo(task, target)} />)}</PriorityQuadrant> })}</div>
      <DragOverlay>{draggedTask ? <PriorityTaskCard draggable={false} task={draggedTask} onComplete={() => undefined} onDelete={() => undefined} onEdit={() => undefined} onMove={() => undefined} /> : null}</DragOverlay>
    </DndContext>
  </>
}

function PriorityFilters({ pillar, state, includePausedProjects, setPillar, setState, setIncludePausedProjects }: { pillar: TaskPillarFilter; state: TaskStateFilter; includePausedProjects: boolean; setPillar: (value: TaskPillarFilter) => void; setState: (value: TaskStateFilter) => void; setIncludePausedProjects: (value: boolean) => void }) { return <section className="priority-filters" aria-label="Filtros de prioridades"><div role="group" aria-label="Filtrar por pilar">{pillars.map((item) => <button className={pillar === item.value ? 'active' : ''} key={item.value} onClick={() => setPillar(item.value)} type="button">{item.label}</button>)}</div><div role="group" aria-label="Filtrar por estado">{([['active', 'Activas'], ['completed', 'Completadas'], ['overdue', 'Vencidas']] as const).map(([value, label]) => <button className={state === value ? 'active' : ''} key={value} onClick={() => setState(value)} type="button">{label}</button>)}</div><label className="priority-paused-filter"><input checked={includePausedProjects} onChange={(event) => setIncludePausedProjects(event.target.checked)} type="checkbox" />Incluir proyectos pausados</label></section> }
function PriorityAxes() { return <div className="priority-axes" aria-hidden="true"><div className="priority-axis-columns"><span>Urgente</span><span>No urgente</span></div><div className="priority-axis-rows"><span>Importante</span><span>No importante</span></div></div> }
function PriorityQuadrant({ quadrant, tasks, children, onCreate, desktop, active, onSelect }: { quadrant: TaskQuadrant; tasks: Task[]; children: ReactNode; onCreate: () => void; desktop: boolean; active: boolean; onSelect: () => void }) { const { isOver, setNodeRef } = useDroppable({ id: quadrant.tone, disabled: !desktop }); return <article aria-labelledby={`quadrant-${quadrant.tone}`} className={`priority-quadrant priority-quadrant--${quadrant.tone} ${isOver ? 'priority-quadrant--over' : ''} ${!desktop && !active ? 'priority-quadrant--hidden-mobile' : ''}`} ref={setNodeRef} role={desktop ? undefined : 'tabpanel'}><button aria-controls={`quadrant-panel-${quadrant.tone}`} aria-selected={active} className="priority-mobile-tab" id={`quadrant-${quadrant.tone}`} onClick={onSelect} role="tab" type="button"><span><small>{quadrant.description}</small><strong>{quadrant.title}</strong></span><b>{tasks.length}</b></button><div className="priority-quadrant-heading" id={`quadrant-panel-${quadrant.tone}`}><div><p>{quadrant.description}</p><h2 id={`quadrant-${quadrant.tone}`}>{quadrant.title}</h2></div><div><span className="quadrant-count">{tasks.length}</span><button aria-label={`Crear tarea en ${quadrant.title}`} className="quadrant-add" onClick={onCreate} type="button"><Plus size={17} /></button></div></div><div className="task-list">{tasks.length ? children : <div className="priority-empty"><Clock3 size={20} /><span>{isOver ? `Soltá para mover a ${quadrant.title}` : 'Sin tareas'}</span></div>}</div></article> }
function PriorityTaskCard({ task, draggable, onComplete, onDelete, onEdit, onMove }: { task: Task; draggable: boolean; onComplete: () => void; onDelete: () => void; onEdit: () => void; onMove: (quadrant: TaskQuadrant) => void }) { const { attributes, listeners, setNodeRef, isDragging } = useDraggable({ id: task.id, disabled: !draggable }); const completed = task.status === 'completed'; const current = findTaskQuadrant(task); return <article className={`task-card ${completed ? 'task-card--completed' : ''} ${isDragging ? 'task-card--dragging' : ''}`} ref={setNodeRef}><div className="task-card-content"><div className="task-card-title"><button aria-label={`Arrastrar ${task.title}`} className="task-drag-handle" {...attributes} {...listeners} type="button"><GripVertical size={16} /></button><h3>{task.title}</h3></div>{task.description && <p>{task.description}</p>}<span>{task.linked_entity_type === 'project' ? 'Proyecto' : task.pillar ?? 'Manual'} · {task.status === 'in_progress' ? 'En curso' : task.status === 'blocked' ? 'En espera' : completed ? 'Hecha' : 'Pendiente'}{isTaskOverdue(task) ? ' · Vencida' : task.due_at ? ` · Vence ${new Intl.DateTimeFormat('es-AR', { dateStyle: 'short' }).format(new Date(task.due_at))}` : ''}</span></div><div className="task-actions"><button aria-label={completed ? 'Reabrir tarea' : 'Completar tarea'} onClick={onComplete} title={completed ? 'Reabrir' : 'Completar'} type="button"><Check size={16} /></button><button aria-label="Editar tarea" onClick={onEdit} title="Editar" type="button"><Pencil size={15} /></button><TaskMoveMenu current={current} onMove={onMove} /><button aria-label="Eliminar tarea" onClick={onDelete} title="Eliminar" type="button"><Trash2 size={15} /></button></div></article> }
function TaskMoveMenu({ current, onMove }: { current: TaskQuadrant; onMove: (quadrant: TaskQuadrant) => void }) { return <label className="task-move-menu"><span className="sr-only">Mover a otro cuadrante</span><select aria-label="Mover a otro cuadrante" onChange={(event) => { const target = taskQuadrants.find((item) => item.tone === event.target.value); if (target) onMove(target) }} value={current.tone}><option value={current.tone}>Mover a…</option>{taskQuadrants.filter((item) => item.tone !== current.tone).map((item) => <option key={item.tone} value={item.tone}>{item.title}</option>)}</select><ChevronDown aria-hidden="true" size={13} /></label> }
function TaskEditor({ task, quadrant, onCancel, onSubmit }: { task?: Task; quadrant?: TaskQuadrant; onCancel: () => void; onSubmit: (input: TaskInput) => Promise<void> }) { const [form, setForm] = useState(() => initialForm(task, quadrant)); const [isSaving, setIsSaving] = useState(false); const change = <K extends keyof FormState>(key: K, value: FormState[K]) => setForm((current) => ({ ...current, [key]: value })); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setIsSaving(true); try { await onSubmit({ title: form.title.trim(), description: form.description.trim() || null, pillar: form.pillar || null, is_urgent: form.urgent, is_important: form.important, due_at: form.dueAt ? new Date(form.dueAt).toISOString() : null, scheduled_at: form.scheduledAt ? new Date(form.scheduledAt).toISOString() : null, estimated_duration_minutes: form.duration ? Number(form.duration) : null, start_at: form.startAt ? new Date(form.startAt).toISOString() : null, energy_required: form.energy || null, focus_mode: form.focus || null }) } finally { setIsSaving(false) } }; return <form className="task-form" onSubmit={submit}><div className="task-form-heading"><h2>{task ? 'Editar tarea' : `Nueva tarea${quadrant ? ` · ${quadrant.title}` : ''}`}</h2><button aria-label="Cerrar formulario" onClick={onCancel} type="button"><X size={18} /></button></div><label>Título<input autoFocus onChange={(event) => change('title', event.target.value)} required value={form.title} /></label><label>Descripción<textarea onChange={(event) => change('description', event.target.value)} value={form.description} /></label><div className="task-form-grid"><label>Pilar<select onChange={(event) => change('pillar', event.target.value)} value={form.pillar}><option value="">Sin pilar</option><option value="health">Salud</option><option value="finance">Finanzas</option><option value="projects">Proyectos</option><option value="habits">Hábitos</option></select></label><label>Duración estimada (min)<input min="1" onChange={(event) => change('duration', event.target.value)} type="number" value={form.duration} /></label><label>Fecha límite<input onChange={(event) => change('dueAt', event.target.value)} type="datetime-local" value={form.dueAt} /></label><label>Fecha programada<input onChange={(event) => change('scheduledAt', event.target.value)} type="datetime-local" value={form.scheduledAt} /></label></div><div className="task-checks"><label><input checked={form.urgent} onChange={(event) => change('urgent', event.target.checked)} type="checkbox" />Urgente</label><label><input checked={form.important} onChange={(event) => change('important', event.target.checked)} type="checkbox" />Importante</label></div><div className="task-form-actions"><button className="secondary-button" onClick={onCancel} type="button">Cancelar</button><button className="primary-button" disabled={isSaving} type="submit">{isSaving ? 'Guardando…' : 'Guardar tarea'}</button></div></form> }
