import { Check, Clock3, Pencil, Plus, Trash2, X } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { useAuth } from '../auth/AuthProvider'
import { taskQuadrants, type Task, type TaskInput, useTaskMutations, useTasks } from './tasks'

type FormState = { title: string; description: string; pillar: string; urgent: boolean; important: boolean; dueAt: string; scheduledAt: string; duration: string }
const toLocalInput = (value: string | null) => value ? value.slice(0, 16) : ''
const initialForm = (task?: Task): FormState => ({ title: task?.title ?? '', description: task?.description ?? '', pillar: task?.pillar ?? '', urgent: task?.is_urgent ?? false, important: task?.is_important ?? false, dueAt: toLocalInput(task?.due_at ?? null), scheduledAt: toLocalInput(task?.scheduled_at ?? null), duration: task?.estimated_duration_minutes?.toString() ?? '' })

export function TasksBoard() {
  const { user } = useAuth(); const { data: tasks = [], isLoading, error } = useTasks(user?.id); const mutations = useTaskMutations(user?.id); const [editingTask, setEditingTask] = useState<Task | null>(null); const [isCreating, setIsCreating] = useState(false)
  if (isLoading) return <div className="tasks-state">Cargando tareas…</div>
  if (error) return <div className="tasks-state tasks-state--error">No se pudieron cargar las tareas. Intentá de nuevo.</div>
  return <><div className="priorities-action"><button className="primary-button" onClick={() => setIsCreating(true)} type="button"><Plus size={18} />Nueva tarea</button></div>{(isCreating || editingTask) && <TaskForm task={editingTask ?? undefined} onCancel={() => { setIsCreating(false); setEditingTask(null) }} onSubmit={async (input) => { if (editingTask) await mutations.updateTask.mutateAsync({ id: editingTask.id, input }); else await mutations.createTask.mutateAsync(input); setIsCreating(false); setEditingTask(null) }} />}{mutations.createTask.error || mutations.updateTask.error || mutations.completeTask.error || mutations.deleteTask.error ? <div className="tasks-state tasks-state--error">No se pudo guardar el cambio. Intentá de nuevo.</div> : null}<section aria-label="Cuadrantes de prioridades" className="priority-grid">{taskQuadrants.map((quadrant) => <article className={`priority-quadrant priority-quadrant--${quadrant.tone}`} key={quadrant.title}><div><p>{quadrant.description}</p><h2>{quadrant.title}</h2></div><div className="task-list">{tasks.filter(quadrant.match).length === 0 ? <div className="priority-empty"><Clock3 size={20} /><span>Sin tareas</span></div> : tasks.filter(quadrant.match).map((task) => <TaskCard key={task.id} task={task} onComplete={() => mutations.completeTask.mutate({ id: task.id, completed: task.status !== 'completed' })} onDelete={() => { if (window.confirm(`¿Eliminar “${task.title}”?`)) mutations.deleteTask.mutate(task.id) }} onEdit={() => setEditingTask(task)} />)}</div></article>)}</section></>
}

function TaskCard({ task, onComplete, onDelete, onEdit }: { task: Task; onComplete: () => void; onDelete: () => void; onEdit: () => void }) {
  const completed = task.status === 'completed'
  return <article className={`task-card ${completed ? 'task-card--completed' : ''}`}><div><h3>{task.title}</h3>{task.description && <p>{task.description}</p>}<span>{task.pillar ?? 'Sin pilar'}{task.estimated_duration_minutes ? ` · ${task.estimated_duration_minutes} min` : ''}</span></div><div className="task-actions"><button aria-label={completed ? 'Reabrir tarea' : 'Completar tarea'} onClick={onComplete} title={completed ? 'Reabrir' : 'Completar'} type="button"><Check size={16} /></button><button aria-label="Editar tarea" onClick={onEdit} title="Editar" type="button"><Pencil size={15} /></button><button aria-label="Eliminar tarea" onClick={onDelete} title="Eliminar" type="button"><Trash2 size={15} /></button></div></article>
}

function TaskForm({ task, onCancel, onSubmit }: { task?: Task; onCancel: () => void; onSubmit: (input: TaskInput) => Promise<void> }) {
  const [form, setForm] = useState(initialForm(task)); const [isSaving, setIsSaving] = useState(false)
  const change = <K extends keyof FormState>(key: K, value: FormState[K]) => setForm((current) => ({ ...current, [key]: value }))
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setIsSaving(true); await onSubmit({ title: form.title.trim(), description: form.description.trim() || null, pillar: form.pillar || null, is_urgent: form.urgent, is_important: form.important, due_at: form.dueAt ? new Date(form.dueAt).toISOString() : null, scheduled_at: form.scheduledAt ? new Date(form.scheduledAt).toISOString() : null, estimated_duration_minutes: form.duration ? Number(form.duration) : null }); setIsSaving(false) }
  return <form className="task-form" onSubmit={submit}><div className="task-form-heading"><h2>{task ? 'Editar tarea' : 'Nueva tarea'}</h2><button aria-label="Cerrar formulario" onClick={onCancel} type="button"><X size={18} /></button></div><label>Título<input onChange={(event) => change('title', event.target.value)} required value={form.title} /></label><label>Descripción<textarea onChange={(event) => change('description', event.target.value)} value={form.description} /></label><div className="task-form-grid"><label>Pilar<select onChange={(event) => change('pillar', event.target.value)} value={form.pillar}><option value="">Sin pilar</option><option value="health">Salud</option><option value="finance">Finanzas</option><option value="projects">Proyectos</option><option value="habits">Hábitos</option></select></label><label>Duración estimada (min)<input min="1" onChange={(event) => change('duration', event.target.value)} type="number" value={form.duration} /></label><label>Fecha límite<input onChange={(event) => change('dueAt', event.target.value)} type="datetime-local" value={form.dueAt} /></label><label>Fecha programada<input onChange={(event) => change('scheduledAt', event.target.value)} type="datetime-local" value={form.scheduledAt} /></label></div><div className="task-checks"><label><input checked={form.urgent} onChange={(event) => change('urgent', event.target.checked)} type="checkbox" />Urgente</label><label><input checked={form.important} onChange={(event) => change('important', event.target.checked)} type="checkbox" />Importante</label></div><div className="task-form-actions"><button className="secondary-button" onClick={onCancel} type="button">Cancelar</button><button className="primary-button" disabled={isSaving} type="submit">{isSaving ? 'Guardando…' : 'Guardar tarea'}</button></div></form>
}
