import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query'
import { supabase } from '../lib/supabase'
import type { Database } from '../types/database'
export type Habit=Database['public']['Tables']['habits']['Row'];export type HabitEntry=Database['public']['Tables']['habit_entries']['Row'];export type HabitInput=Pick<Habit,'name'|'description'|'frequency_type'|'target_count'|'days_of_week'|'start_date'|'end_date'>
export const habitsKey=(id:string)=>['habits',id] as const;const need=<T,>(r:{data:T|null,error:{message:string}|null})=>{if(r.error)throw new Error(r.error.message);if(r.data===null)throw new Error('Sin respuesta.');return r.data};export const habitToday=()=>new Date().toLocaleDateString('en-CA')
export function useHabits(id: string | undefined) {
  return useQuery({ queryKey: habitsKey(id ?? ''), enabled: Boolean(id), retry: false, queryFn: async () => {
    const habits = need(await supabase.from('habits').select('*').eq('user_id', id!).order('created_at'))
    const entries = habits.length ? need(await supabase.from('habit_entries').select('*').eq('user_id', id!).in('habit_id', habits.map((habit) => habit.id)).order('entry_date', { ascending: false })) : []
    return { habits, entries }
  } })
}
export function useHabitMutations(id:string|undefined){const c=useQueryClient();const done=async()=>{if(id)await c.invalidateQueries({queryKey:habitsKey(id)})};return{create:useMutation({retry:false,mutationFn:async(input:HabitInput)=>need(await supabase.from('habits').insert({...input,user_id:id!,pillar:'habits',linked_entity_type:null,linked_entity_id:null}).select().single()),onSuccess:done}),update:useMutation({retry:false,mutationFn:async({id:row,input}:{id:string;input:HabitInput})=>need(await supabase.from('habits').update(input).eq('id',row).eq('user_id',id!).select().single()),onSuccess:done}),toggle:useMutation({retry:false,mutationFn:async({id:row,is_active}:{id:string;is_active:boolean})=>need(await supabase.from('habits').update({is_active}).eq('id',row).eq('user_id',id!).select().single()),onSuccess:done}),entry:useMutation({retry:false,mutationFn:async({habit,count}:{habit:string;count:number})=>need(await supabase.from('habit_entries').upsert({user_id:id!,habit_id:habit,entry_date:habitToday(),completed_count:count},{onConflict:'habit_id,entry_date'}).select().single()),onSuccess:done}),remove:useMutation({retry:false,mutationFn:async(row:string)=>need(await supabase.from('habits').delete().eq('id',row).eq('user_id',id!).select('id').single()),onSuccess:done})}}
export function habitSummary(habits:Habit[],entries:HabitEntry[]){const today=habitToday();const active=habits.filter(h=>h.is_active);const completed=active.filter(h=>(entries.find(e=>e.habit_id===h.id&&e.entry_date===today)?.completed_count??0)>=h.target_count).length;const monday=new Date();monday.setDate(monday.getDate()-((monday.getDay()+6)%7));const weekly=entries.filter(e=>new Date(`${e.entry_date}T00:00:00`)>=monday);const total=active.reduce((s,h)=>s+h.target_count,0);return{active,completed,weeklyPercent:total?Math.min(100,weekly.reduce((s,e)=>s+e.completed_count,0)/total*100):0}}
export function isHabitApplicable(habit: Habit, date: Date) { if (!habit.is_active || date < new Date(`${habit.start_date}T00:00:00`) || (habit.end_date && date > new Date(`${habit.end_date}T00:00:00`))) return false; return habit.frequency_type !== 'specific_days' || habit.days_of_week?.includes(date.getDay()) === true }
export function habitStreaks(habit: Habit, entries: HabitEntry[], reference = new Date()) { let current = 0, best = 0, running = 0; const cursor = new Date(reference); cursor.setHours(0,0,0,0); for (let offset = 0; offset < 365; offset += 1) { const date = new Date(cursor); date.setDate(cursor.getDate() - offset); if (!isHabitApplicable(habit, date)) continue; const key = date.toLocaleDateString('en-CA'); const completed = (entries.find((entry) => entry.habit_id === habit.id && entry.entry_date === key)?.completed_count ?? 0) >= habit.target_count; if (completed) { running += 1; best = Math.max(best, running); if (offset === 0 || current === running - 1) current = running } else { if (offset === 0 || current === running) current = running; running = 0 } } return { current, best } }
export function lastThirtyDays(habit: Habit, entries: HabitEntry[]) { return Array.from({ length: 30 }, (_, index) => { const date = new Date(); date.setHours(0,0,0,0); date.setDate(date.getDate() - (29 - index)); const key = date.toLocaleDateString('en-CA'); return { date: key, applicable: isHabitApplicable(habit, date), completed: (entries.find((entry) => entry.habit_id === habit.id && entry.entry_date === key)?.completed_count ?? 0) >= habit.target_count } }) }
