import { AlertTriangle, Check, Coffee, Link, Moon, Plus, Sunrise } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { useAuth } from '../auth/AuthProvider'
import { generalStreak, getDailySummary, getEntryProgress, getHabitAnalytics, getRiskHabits, isHabitSuccessful, habitStreaks, habitToday, type Habit, type HabitEntry, type HabitInput, useHabitMutations, useHabitRoutineMutations, useHabitRoutines, useHabits } from './habits'

const groups = [
  { key: 'morning', label: 'Mañana', Icon: Sunrise }, { key: 'afternoon', label: 'Tarde', Icon: Coffee },
  { key: 'evening', label: 'Noche', Icon: Moon }, { key: 'before_sleep', label: 'Antes de dormir', Icon: Moon }, { key: 'anytime', label: 'En cualquier momento', Icon: Check },
] as const

export function HabitsPage() {
  const { user } = useAuth(); const query = useHabits(user?.id); const routinesQuery = useHabitRoutines(user?.id); const mutations = useHabitMutations(user?.id); const routineMutations = useHabitRoutineMutations(user?.id); const [open, setOpen] = useState(false); const [routineOpen, setRoutineOpen] = useState(false)
  if (query.isLoading) return <div className="page"><div className="tasks-state">Cargando hábitos…</div></div>
  if (query.error || !query.data) return <div className="page"><div className="tasks-state tasks-state--error">No se pudieron cargar los hábitos.</div></div>
  const { habits, entries, pauses, preferences } = query.data; const today = habitToday(); const summary = getDailySummary(habits, entries, pauses); const streak = generalStreak(habits, entries, pauses, preferences?.general_streak_threshold ?? .8); const risks = getRiskHabits(habits, entries, pauses); const analytics = getHabitAnalytics(habits, entries, pauses)
  return <div className="page habits-dashboard">
    <header className="page-header"><div><p className="eyebrow">Pilar personal</p><h1>Hábitos</h1><p className="page-description">Pequeñas acciones, constancia visible.</p></div><button className="primary-button" onClick={() => setOpen(true)} type="button"><Plus size={18} />Nuevo hábito</button></header>
    {open && <HabitForm onCancel={() => setOpen(false)} onSave={async (input) => { await mutations.create.mutateAsync(input); setOpen(false) }} />}
    <section className="habits-kpi-grid" aria-label="Resumen de hábitos">
      <Kpi label="Puntuación de hoy" value={`${summary.score.toFixed(0)}%`} detail="Solo hábitos aplicables" />
      <Kpi label="Completados" value={`${summary.completed}/${summary.applicable.length}`} detail="Éxitos completos de hoy" />
      <Kpi label="Racha general" value={`${streak.current} días`} detail="Días con 80% o más" />
      <Kpi label="Mejor racha" value={`${streak.best} días`} detail="Máxima constancia registrada" />
      <Kpi label="En riesgo" value={String(risks.length)} detail="Revisá antes de cerrar el día" tone={risks.length ? 'warning' : undefined} />
    </section>
    <section className="habits-today content-card"><div className="section-heading"><div><p className="eyebrow">Registro rápido</p><h2>Hoy</h2></div><span className="section-status">{today}</span></div>
      {groups.map(({ key, label, Icon }) => { const groupHabits = habits.filter((habit) => habit.time_of_day === key); return groupHabits.length ? <section className="habit-time-group" key={key}><h3><Icon size={16} />{label}</h3>{groupHabits.map((habit) => <HabitQuickEntry key={habit.id} habit={habit} entry={entries.find((item) => item.habit_id === habit.id && item.entry_date === today)} entries={entries} onEntry={(value, status) => mutations.entry.mutate({ habit, date: today, value, status })} onPause={() => mutations.pause.mutate({ habit, paused: habit.is_active })} />)}</section> : null })}
      {!habits.length && <div className="tasks-state">Todavía no hay hábitos. Creá uno para empezar con un registro simple.</div>}
    </section>
    <section className="habits-lower-grid"><article className="content-card"><div className="section-heading"><h2>Avance semanal</h2></div>{summary.weeklyProgress.length ? <div className="habit-weekly-list">{summary.weeklyProgress.map(({ habit, value }) => <div key={habit.id}><span>{habit.name}</span><strong>{value}/{habit.target_value}</strong></div>)}</div> : <p className="empty-copy">No hay hábitos con meta semanal.</p>}</article><article className="content-card"><div className="section-heading"><h2>Hábitos en riesgo</h2></div>{risks.length ? <ul className="habit-risk-list">{risks.map((habit) => <li key={habit.id}><AlertTriangle size={16} />{habit.name}</li>)}</ul> : <p className="empty-copy">Todo bajo control por ahora.</p>}</article></section>
    <section className="habits-routines"><div className="section-heading"><div><p className="eyebrow">Habit stacking</p><h2>Rutinas</h2></div><button className="secondary-button" onClick={() => setRoutineOpen(true)} type="button"><Plus size={16} />Nueva rutina</button></div>{routineOpen && <RoutineForm habits={habits.filter((habit) => habit.is_active)} onCancel={() => setRoutineOpen(false)} onSave={async (input) => { await routineMutations.create.mutateAsync(input); setRoutineOpen(false) }} />}{routinesQuery.isLoading ? <div className="tasks-state">Cargando rutinas…</div> : routinesQuery.data?.routines.length ? <div className="habit-routine-grid">{routinesQuery.data.routines.map((routine) => <RoutineCard key={routine.id} routine={routine} items={routinesQuery.data!.items.filter((item) => item.routine_id === routine.id)} habits={habits} entries={entries} onToggle={() => routineMutations.toggle.mutate({ id: routine.id, isActive: !routine.is_active })} onRemove={() => { if (window.confirm('¿Eliminar rutina? Los hábitos no se eliminarán.')) routineMutations.remove.mutate(routine.id) }} />)}</div> : <div className="tasks-state">Todavía no hay rutinas. Encadená hábitos existentes sin duplicarlos.</div>}</section>
    <section className="habits-analytics"><div className="section-heading"><div><p className="eyebrow">Seguimiento</p><h2>Constancia</h2></div><span className="section-status">Basado en oportunidades aplicables</span></div><div className="habits-analysis-kpis"><Kpi label="Días activos" value={String(analytics.activeDays)} detail="En los últimos 12 meses" /><Kpi label="Consistencia" value={`${analytics.consistency.toFixed(0)}%`} detail={`Últimas ${analytics.opportunityCount} oportunidades`} /><Kpi label="Nivel actual" value={analytics.consistencyLevel} detail="Indicador descriptivo, no científico" /></div><div className="habits-analysis-grid"><HabitHeatmap days={analytics.monthDays} /><HabitWeeklyMatrix matrix={analytics.matrix} /><HabitYearOverview months={analytics.months} /></div></section>
  </div>
}

function Kpi({ label, value, detail, tone }: { label: string; value: string; detail: string; tone?: 'warning' }) { return <article className={`habit-kpi${tone ? ` habit-kpi--${tone}` : ''}`}><p>{label}</p><strong>{value}</strong><small>{detail}</small></article> }

function level(score: number | null) { return score === null ? 0 : score === 0 ? 1 : score < 50 ? 2 : score < 85 ? 3 : 4 }
function HabitHeatmap({ days }: { days: { date: string; score: number | null }[] }) { const first = days[0] ? new Date(`${days[0].date}T12:00:00`).getDay() : 0; return <article className="content-card habit-analysis-card"><div className="section-heading"><h2>Mapa mensual</h2></div><p className="empty-copy">La intensidad representa el porcentaje del día.</p><div className="habit-heatmap" style={{ gridTemplateColumns: 'repeat(7, 1fr)' }}>{Array.from({ length: (first + 6) % 7 }, (_, index) => <i className="habit-heatmap-empty" key={`empty-${index}`} />)}{days.map((day) => <i className={`habit-heatmap-level-${level(day.score)}`} key={day.date} title={`${day.date}${day.score === null ? ': sin oportunidad' : `: ${day.score.toFixed(0)}%`}`} />)}</div><div className="habit-heatmap-legend"><span>Sin oportunidad</span><span>0%</span><span>Parcial</span><span>Alto</span><span>100%</span></div></article> }
function HabitWeeklyMatrix({ matrix }: { matrix: ReturnType<typeof getHabitAnalytics>['matrix'] }) { const labels = ['L', 'M', 'X', 'J', 'V', 'S', 'D']; return <article className="content-card habit-analysis-card"><div className="section-heading"><h2>Matriz semanal</h2></div>{matrix.length ? <div className="habit-matrix"><div className="habit-matrix__row habit-matrix__header"><span>Hábito</span>{labels.map((label) => <b key={label}>{label}</b>)}</div>{matrix.map(({ habit, days }) => <div className="habit-matrix__row" key={habit.id}><span title={habit.name}>{habit.name}</span>{days.map((day) => <i className={`habit-matrix-level-${level(day.progress === null ? null : day.progress * 100)}`} key={day.date} title={day.date} />)}</div>)}</div> : <p className="empty-copy">Todavía no hay hábitos diarios para mostrar.</p>}</article> }
function HabitYearOverview({ months }: { months: ReturnType<typeof getHabitAnalytics>['months'] }) { return <article className="content-card habit-analysis-card"><div className="section-heading"><h2>Vista anual</h2></div><p className="empty-copy">Promedio de cumplimiento por mes.</p><div className="habit-year-overview">{months.map((month) => <div key={month.label}><i className={`habit-year-level-${level(month.score)}`} /><span>{month.label.replace('.', '')}</span><strong>{month.score === null ? '—' : `${month.score.toFixed(0)}%`}</strong></div>)}</div></article> }

function HabitQuickEntry({ habit, entry, entries, onEntry, onPause }: { habit: Habit; entry: HabitEntry | undefined; entries: HabitEntry[]; onEntry: (value: number | null, status: 'completed' | 'partial' | 'avoided' | 'occurred' | null) => void; onPause: () => void }) {
  const progress = getEntryProgress(habit, entry); const streak = habitStreaks(habit, entries); const value = entry?.value ?? entry?.completed_count ?? 0
  const complete = () => { if (habit.habit_type === 'break') onEntry(null, entry?.status === 'avoided' ? null : 'avoided'); else if (habit.tracking_type === 'binary') onEntry(null, entry?.status === 'completed' ? null : 'completed'); else { const next = value >= habit.target_value ? 0 : value + 1; onEntry(next, next >= habit.minimum_success_value ? 'completed' : 'partial') } }
  const occurrence = () => onEntry(Math.max(1, value + 1), 'occurred')
  return <article className="habit-quick-entry"><div className="habit-quick-entry__main"><strong>{habit.name}</strong><p>{!habit.is_active ? 'En pausa' : habit.habit_type === 'break' ? (entry?.status === 'avoided' ? 'Día evitado' : entry?.status === 'occurred' ? 'Ocurrencia registrada' : 'Confirmá si lo evitaste') : habit.tracking_type === 'binary' ? (entry?.status === 'completed' ? 'Completado' : 'Pendiente') : `${value}${habit.unit ? ` ${habit.unit}` : ''} de ${habit.target_value}${habit.unit ? ` ${habit.unit}` : ''}`}</p><span className="habit-progress"><i style={{ width: `${progress * 100}%` }} /></span><small>Racha {streak.current} · mejor {streak.best}</small></div><div className="habit-quick-entry__actions">{habit.is_active && <><button className="primary-button" onClick={complete} type="button">{habit.habit_type === 'break' ? (entry?.status === 'avoided' ? 'Deshacer' : 'Lo evité') : habit.tracking_type === 'binary' ? (entry?.status === 'completed' ? 'Desmarcar' : 'Completar') : '+1'}</button>{habit.habit_type === 'break' && <button className="secondary-button" onClick={occurrence} type="button">Registrar ocurrencia</button>}</>}<button className="text-button" onClick={onPause} type="button">{habit.is_active ? 'Pausar' : 'Reactivar'}</button></div></article>
}

function RoutineCard({ routine, items, habits, entries, onToggle, onRemove }: { routine: { id: string; name: string; time_of_day: string | null; is_active: boolean }; items: { habit_id: string; position: number; trigger_text: string | null }[]; habits: Habit[]; entries: HabitEntry[]; onToggle: () => void; onRemove: () => void }) { const ordered = [...items].sort((first, second) => first.position - second.position).map((item) => ({ item, habit: habits.find((habit) => habit.id === item.habit_id) })).filter((value): value is { item: typeof items[number]; habit: Habit } => Boolean(value.habit)); const done = ordered.filter(({ habit }) => isHabitSuccessful(habit, entries.find((entry) => entry.habit_id === habit.id && entry.entry_date === habitToday()))).length; return <article className={`habit-routine-card${routine.is_active ? '' : ' habit-routine-card--paused'}`}><div className="habit-routine-card__heading"><div><span><Link size={14} />{routine.time_of_day ?? 'Cualquier momento'}</span><h3>{routine.name}</h3></div><strong>{done}/{ordered.length}</strong></div>{ordered[0]?.item.trigger_text && <p className="habit-routine-trigger">Después de: {ordered[0].item.trigger_text}</p>}<ol>{ordered.map(({ item, habit }) => <li className={isHabitSuccessful(habit, entries.find((entry) => entry.habit_id === habit.id && entry.entry_date === habitToday())) ? 'done' : ''} key={item.habit_id}>{habit.name}</li>)}</ol><div className="habit-routine-actions"><button className="text-button" onClick={onToggle} type="button">{routine.is_active ? 'Pausar rutina' : 'Reactivar'}</button><button className="text-button" onClick={onRemove} type="button">Eliminar</button></div></article> }

function RoutineForm({ habits, onCancel, onSave }: { habits: Habit[]; onCancel: () => void; onSave: (input: { name: string; timeOfDay: string | null; triggerText: string | null; habitIds: string[] }) => Promise<void> }) { const [name, setName] = useState(''); const [trigger, setTrigger] = useState(''); const [time, setTime] = useState(''); const [selected, setSelected] = useState<string[]>([]); const toggle = (id: string) => setSelected((current) => current.includes(id) ? current.filter((habitId) => habitId !== id) : [...current, id]); return <form className="task-form habit-routine-form" onSubmit={async (event) => { event.preventDefault(); await onSave({ name, timeOfDay: time || null, triggerText: trigger || null, habitIds: selected }) }}><div className="task-form-heading"><h2>Nueva rutina</h2></div><label>Nombre<input onChange={(event) => setName(event.target.value)} required value={name} /></label><div className="task-form-grid"><label>Disparador<input onChange={(event) => setTrigger(event.target.value)} placeholder="Después de tomar mate" value={trigger} /></label><label>Momento<select onChange={(event) => setTime(event.target.value)} value={time}><option value="">Cualquier momento</option>{groups.map((group) => <option key={group.key} value={group.key}>{group.label}</option>)}</select></label></div><fieldset className="habit-routine-selector"><legend>Hábitos en orden</legend>{habits.map((habit) => <label key={habit.id}><input checked={selected.includes(habit.id)} onChange={() => toggle(habit.id)} type="checkbox" />{habit.name}</label>)}</fieldset><div className="task-form-actions"><button className="secondary-button" onClick={onCancel} type="button">Cancelar</button><button className="primary-button" disabled={!selected.length} type="submit">Guardar rutina</button></div></form> }

function HabitForm({ onCancel, onSave }: { onCancel: () => void; onSave: (input: HabitInput) => Promise<void> }) {
  const [name, setName] = useState(''); const [frequency, setFrequency] = useState('daily'); const [habitType, setHabitType] = useState('build'); const [trackingType, setTrackingType] = useState('binary'); const [target, setTarget] = useState('1'); const [unit, setUnit] = useState(''); const [time, setTime] = useState('anytime')
  const submit = async (event: FormEvent) => { event.preventDefault(); const targetValue = Number(target); await onSave({ name, description: null, frequency_type: frequency, target_count: targetValue, days_of_week: frequency === 'specific_days' ? [0, 1, 2, 3, 4, 5, 6] : null, start_date: habitToday(), end_date: null, habit_type: habitType, tracking_type: trackingType, time_of_day: time, target_value: targetValue, unit: unit || null, minimum_success_value: targetValue }) }
  return <form className="task-form" onSubmit={submit}><div className="task-form-heading"><h2>Nuevo hábito</h2></div><label>Nombre<input onChange={(event) => setName(event.target.value)} required value={name} /></label><div className="task-form-grid"><label>Tipo<select onChange={(event) => setHabitType(event.target.value)} value={habitType}><option value="build">Construir</option><option value="break">Romper</option></select></label><label>Registro<select onChange={(event) => setTrackingType(event.target.value)} value={trackingType}><option value="binary">Binario</option><option value="count">Contador</option><option value="duration">Duración</option><option value="quantitative">Cuantitativo</option></select></label><label>Frecuencia<select onChange={(event) => setFrequency(event.target.value)} value={frequency}><option value="daily">Diaria</option><option value="specific_days">Días específicos</option><option value="weekly_count">Cantidad semanal</option></select></label><label>Momento<select onChange={(event) => setTime(event.target.value)} value={time}>{groups.map((group) => <option key={group.key} value={group.key}>{group.label}</option>)}</select></label></div>{trackingType !== 'binary' && <div className="task-form-grid"><label>Meta<input min="1" onChange={(event) => setTarget(event.target.value)} required type="number" value={target} /></label><label>Unidad<input onChange={(event) => setUnit(event.target.value)} placeholder="min, vasos, páginas…" value={unit} /></label></div>}<div className="task-form-actions"><button className="secondary-button" onClick={onCancel} type="button">Cancelar</button><button className="primary-button" type="submit">Guardar</button></div></form>
}
