import { CirclePause, FolderKanban, ListChecks, Plus, Target } from 'lucide-react'
import { useState, type FormEvent, type ReactNode } from 'react'
import { NavLink } from 'react-router-dom'
import { useAuth } from '../auth/AuthProvider'
import { projectProgress, useProjectMutations, useProjectsWorkspace, type ProjectInput } from './projects'

const month = () => new Date().toISOString().slice(0, 7)
export function ProjectsPage() {
  const { user } = useAuth(); const workspace = useProjectsWorkspace(user?.id, month()); const mutations = useProjectMutations(user?.id); const [open, setOpen] = useState(false)
  if (workspace.isLoading) return <div className="page"><div className="tasks-state">Cargando proyectos…</div></div>
  if (workspace.error || !workspace.data || !workspace.tasks.data) return <div className="page"><div className="tasks-state tasks-state--error">No se pudieron cargar proyectos.</div></div>
  const data = workspace.data
  return <div className="page projects-dashboard"><header className="page-header"><div><p className="eyebrow">Pilar personal</p><h1>Proyectos</h1><p className="page-description">Claridad para ejecutar, priorizar y sostener el avance.</p></div><button className="primary-button" onClick={() => setOpen(true)} type="button"><Plus size={18} />Nuevo proyecto</button></header>
    {open && <ProjectForm onCancel={() => setOpen(false)} onSave={async (input) => { await mutations.create.mutateAsync(input); setOpen(false) }} />}
    <section className="project-kpi-grid"><Kpi icon={<FolderKanban size={18} />} label="Activos" value={String(data.active.length)} detail="En ejecución" /><Kpi icon={<CirclePause size={18} />} label="Pausados" value={String(data.paused.length)} detail="No generan alertas" /><Kpi icon={<Target size={18} />} label="Completados" value={String(data.completed.length)} detail="Este mes" /><Kpi icon={<ListChecks size={18} />} label="Tasa de avance" value={data.progress === null ? 'Sin datos' : `${data.progress.toFixed(0)}%`} detail={data.progress === null ? 'Sin tareas válidas' : `${data.completedTasks}/${data.totalTasks} tareas válidas`} /><Kpi icon={<Target size={18} />} label="Horas esta semana" value="Sin sesiones" detail="Próxima fase" /><Kpi icon={<Target size={18} />} label="Racha de enfoque" value="Sin sesiones" detail="Próxima fase" /></section>
    <section className="project-focus-card"><div><p className="eyebrow">Siguiente acción prioritaria</p><h2>{data.next?.task.title ?? 'No hay una acción elegible'}</h2><p>{data.next ? `${data.next.reason}. Se prioriza Eisenhower, vencimiento, programación, orden y creación.` : 'Las tareas de proyectos pausados y finalizados no se consideran.'}</p></div>{data.next && <NavLink className="secondary-button" to={`/proyectos/${data.next.task.linked_entity_id}`}>Ver proyecto</NavLink>}</section>
    <section className="content-card"><div className="section-heading"><div><p className="eyebrow">Ejecución</p><h2>Proyectos activos</h2></div></div>{data.active.length ? <div className="project-card-list">{data.active.map((project) => { const progress = projectProgress(project, workspace.tasks.data!); return <NavLink className="project-summary-card" key={project.id} to={`/proyectos/${project.id}`}><div><strong>{project.name}</strong><p>{project.priority === 'high' ? 'Prioridad alta' : project.priority === 'medium' ? 'Prioridad media' : 'Prioridad baja'} · {progress.total ? `${progress.completed}/${progress.total} tareas` : 'Sin tareas'}</p></div><div><strong>{progress.percent === null ? '—' : `${progress.percent.toFixed(0)}%`}</strong><span className="mini-progress"><i style={{ width: `${progress.percent ?? 0}%` }} /></span></div></NavLink>})}</div> : <div className="tasks-state">Todavía no hay proyectos activos.</div>}</section>
  </div>
}
function Kpi({ icon, label, value, detail }: { icon: ReactNode; label: string; value: string; detail: string }) { return <article className="project-kpi"><span>{icon}</span><p>{label}</p><strong>{value}</strong><small>{detail}</small></article> }
function ProjectForm({ onCancel, onSave }: { onCancel: () => void; onSave: (input: ProjectInput) => Promise<void> }) { const [name, setName] = useState(''); const [priority, setPriority] = useState('medium'); const submit = async (event: FormEvent) => { event.preventDefault(); await onSave({ name: name.trim(), description: null, status: 'active', priority, start_date: null, due_date: null }) }; return <form className="task-form" onSubmit={submit}><label>Nombre<input onChange={(event) => setName(event.target.value)} required value={name} /></label><label>Prioridad<select onChange={(event) => setPriority(event.target.value)} value={priority}><option value="low">Baja</option><option value="medium">Media</option><option value="high">Alta</option></select></label><div className="task-form-actions"><button className="secondary-button" onClick={onCancel} type="button">Cancelar</button><button className="primary-button" type="submit">Guardar</button></div></form> }
