import { CirclePause, FolderKanban, ListChecks, Plus, Target } from 'lucide-react'
import { useEffect, useState, type FormEvent, type ReactNode } from 'react'
import { NavLink, useLocation } from 'react-router-dom'
import { useAuth } from '../auth/AuthProvider'
import { QUICK_ACTION_EVENT, useUndoToast } from '../quick-actions/QuickActions'
import { projectProgress, useProjectMutations, useProjectsWorkspace, type Project, type ProjectInput } from './projects'

const month = () => new Date().toISOString().slice(0, 7)
export function ProjectsPage() {
  const { user } = useAuth(); const location = useLocation(); const requestedAction = (location.state as { openAction?: string } | null); const workspace = useProjectsWorkspace(user?.id, month()); const mutations = useProjectMutations(user?.id); const [open, setOpen] = useState(() => requestedAction?.openAction === 'project'); const { notify } = useUndoToast()
  useEffect(() => { const handle = (event: Event) => { if ((event as CustomEvent<string>).detail === 'project') setOpen(true) }; window.addEventListener(QUICK_ACTION_EVENT, handle); return () => window.removeEventListener(QUICK_ACTION_EVENT, handle) }, [])
  if (workspace.isLoading) return <div className="page"><div className="tasks-state">Cargando proyectos…</div></div>
  if (workspace.error || !workspace.data || !workspace.tasks.data) return <div className="page"><div className="tasks-state tasks-state--error">No se pudieron cargar proyectos.</div></div>
  const data = workspace.data
  return <div className="page projects-dashboard"><header className="page-header"><div><p className="eyebrow">Pilar personal</p><h1>Proyectos</h1><p className="page-description">Claridad para ejecutar, priorizar y sostener el avance.</p></div><button className="primary-button" onClick={() => setOpen(true)} type="button"><Plus size={18} />Nuevo proyecto</button></header>
    {open && <ProjectForm onCancel={() => setOpen(false)} onSave={async (input) => { const created = await mutations.create.mutateAsync(input) as Project; setOpen(false); notify({ message: 'Proyecto creado.', undo: () => mutations.remove.mutateAsync(created.id) }) }} />}
    <section className="project-kpi-grid"><Kpi icon={<FolderKanban size={18} />} label="Activos" value={String(data.active.length)} detail="En ejecución" /><Kpi icon={<CirclePause size={18} />} label="Pausados" value={String(data.paused.length)} detail="No generan alertas" /><Kpi icon={<Target size={18} />} label="Completados" value={String(data.completed.length)} detail="Este mes" /><Kpi icon={<ListChecks size={18} />} label="Tasa de avance" value={data.progress === null ? 'Sin datos' : `${data.progress.toFixed(0)}%`} detail={data.progress === null ? 'Sin tareas válidas' : `${data.completedTasks}/${data.totalTasks} tareas válidas`} /><Kpi icon={<Target size={18} />} label="Horas esta semana" value="Sin sesiones" detail="Próxima fase" /><Kpi icon={<Target size={18} />} label="Racha de enfoque" value="Sin sesiones" detail="Próxima fase" /></section>
    <section className="project-focus-card"><div><p className="eyebrow">Siguiente acción prioritaria</p><h2>{data.next?.task.title ?? 'No hay una acción elegible'}</h2><p>{data.next ? `${data.next.reason}. Se prioriza Eisenhower, vencimiento, programación, orden y creación.` : 'Las tareas de proyectos pausados y finalizados no se consideran.'}</p></div>{data.next && <NavLink className="secondary-button" to={`/proyectos/${data.next.task.linked_entity_id}`}>Ver proyecto</NavLink>}</section>
    <section className="content-card"><div className="section-heading"><div><p className="eyebrow">Ejecución</p><h2>Proyectos activos</h2></div></div>{data.active.length ? <div className="project-card-list">{data.active.map((project) => { const progress = projectProgress(project, workspace.tasks.data!); return <NavLink className="project-summary-card" key={project.id} to={`/proyectos/${project.id}`}><div><strong>{project.name}</strong><p>{project.priority === 'high' ? 'Prioridad alta' : project.priority === 'medium' ? 'Prioridad media' : 'Prioridad baja'} · {progress.total ? `${progress.completed}/${progress.total} tareas` : 'Sin tareas'}</p></div><div><strong>{progress.percent === null ? '—' : `${progress.percent.toFixed(0)}%`}</strong><span className="mini-progress"><i style={{ width: `${progress.percent ?? 0}%` }} /></span></div></NavLink>})}</div> : <div className="tasks-state">Todavía no hay proyectos activos.</div>}</section>
  </div>
}
function Kpi({ icon, label, value, detail }: { icon: ReactNode; label: string; value: string; detail: string }) { return <article className="project-kpi"><span>{icon}</span><p>{label}</p><strong>{value}</strong><small>{detail}</small></article> }
function ProjectForm({ onCancel, onSave }: { onCancel: () => void; onSave: (input: ProjectInput) => Promise<void> }) { const [name, setName] = useState(''); const [priority, setPriority] = useState('medium'); const [description, setDescription] = useState(''); const [startDate, setStartDate] = useState(''); const [dueDate, setDueDate] = useState(''); const [advanced, setAdvanced] = useState(false); const [saving, setSaving] = useState(false); const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); try { await onSave({ name: name.trim(), description: description.trim() || null, status: 'active', priority, start_date: startDate || null, due_date: dueDate || null }) } finally { setSaving(false) } }; return <form className="task-form" onSubmit={submit}><label>Nombre<input autoFocus onChange={(event) => setName(event.target.value)} required value={name} /></label><fieldset className="chip-field"><legend>Prioridad</legend><div className="choice-chips">{([['low','Baja'],['medium','Media'],['high','Alta']] as const).map(([value,label]) => <button className={priority === value ? 'active' : ''} key={value} onClick={() => setPriority(value)} type="button">{label}</button>)}</div></fieldset><button aria-expanded={advanced} className="text-button disclosure-button" onClick={() => setAdvanced((value) => !value)} type="button">{advanced ? 'Menos opciones' : 'Más opciones'}</button>{advanced && <div className="progressive-fields"><label>Descripción<textarea onChange={(event) => setDescription(event.target.value)} value={description}/></label><div className="task-form-grid"><label>Inicio<input onChange={(event) => setStartDate(event.target.value)} type="date" value={startDate}/></label><label>Fecha límite<input min={startDate || undefined} onChange={(event) => setDueDate(event.target.value)} type="date" value={dueDate}/></label></div></div>}<div className="task-form-actions"><button className="secondary-button" onClick={onCancel} type="button">Cancelar</button><button className="primary-button" disabled={saving} type="submit">{saving ? 'Guardando…' : 'Crear proyecto'}</button></div></form> }
